### ISSUE TITLE
Audio mute button/MPB14,1 shown as MBA

### ISSUE THREAD

**Issue by egore24** [the-darkvoid/XPS9360-macOS#1]
Hey darkvoid. Thank you for the excellent work for our machine!

Two issues I have discovered so far...the keyboard mute button does not mute the sound. Graphically, it represents correctly on screen, but sound remains on.

Other, using MBP14,1 SMBIOS info in iCloud devices and other locations is reported as a MacBook Air. This might be a Clover issue, but if there is something we can do to correct that, it'd be great.

Thanks again.

**Comment by the-darkvoid** [comment]
@egore24,

Give audio a try with these new updates. 

To update:

- Integrate updated `SSDT-Config.dsl`
- Integrate updated `SSDT-ALC256.dsl`
- Generate new `AppleHDA_ALC256.kext` using `XPS9360.sh` script.

I will take a look into the MacBook Air issue, but its probably better to raise that as a separate issue and track it with more detail.
