### ISSUE TITLE
Battery percentage in the menu bar

### ISSUE THREAD

**Issue by egore24** [the-darkvoid/XPS9360-macOS#10]
Hello DV. I'm having an issue with the menu bar representation of the battery status. It doesn't accurately track the percentage value, however if I deselect show percentage and then reselect show percentage it updates correctly. After sometime though, it again stops tracking the percentage of the battery. Also, upon restart the battery menu bar battery icon disappears altogether. It then needs to be reselected to be shown from the energy saver control panel.

Thanks for everything!

**Comment by egore24** [comment]
Been trying to solve this problem, I found that disabling TRIM might fix this. Sending the sudo trimforce  disable does not disable trim with your configuration/files. How can I actually disable TRIM to see if that's the problem? Thanks much!

**Comment by egore24** [comment]
APFS doesn't allow TRIM to be disabled, apparently. How do you manage this issue? Have you found a good value for PollDelay on our machines to help in some way?

**Comment by the-darkvoid** [comment]
@egore24, battery tracking on APFS with TRIM is a known problem. It seems to be getting better as macOS versions move along, it hasn't really bothered me too much.

Closing until an update for org.rehabman.driver.AppleSmartBatteryManager comes along.
