### ISSUE TITLE
GPU drag down CPU clock speed.

### ISSUE THREAD

**Issue by businessman9** [the-darkvoid/XPS9360-macOS#100]
In daily usage everything works well.
I use an app "Timestamp Photo and Video" to add timecode in the video,
and when it's rendering videos CPU clock speed is locked under 1 GHz if GPU is also working.
[here is the screenshot](https://imgur.com/T03w2Uh)

I tried with CINEBENCH R15 OPENGL test and it's the same.
[Intel Power Gadget](https://imgur.com/eTivdLk)

**Comment by 13xps** [comment]
Have you tried in windows? I found the CPU power profile is very weak on osx. I can sustain around 3.2 constant in W10, but in Mojave using this repo its like 2.2 max. Wish there was a fix for this.

**Comment by businessman9** [comment]
I tried in windows 10, CPU and GPU do great with both cinebench and video rendering, CPU can go up to 3.x GHz when GPU is doing some work.

**Comment by 13xps** [comment]
Yup, same here. Really sucks that we are gimped on OSX. This was so close to being a perfect solution to an overpriced Macbook. Hopefully the-darkvoid comes out with a solution one day...

**Comment by 13xps** [comment]
If you find a solution for OSX please update this.

**Comment by dkkyeremateng** [comment]
I have the 9360 i5-8250U FHD 8GB and I'm getting 3.4GHz on 10.13.5. Everything work great on High Sierra but I'm yet to update to Mojave

**Comment by businessman9** [comment]
It turns out that Dell sets a TDP limit in BIOS.
I read [this](https://www.reddit.com/r/macbookpro/comments/91256u/optimal_cpu_tuning_settings_for_i9_mbp_to_stop/) about VRM throttling and tried to edit CPU MSR settings. I was able to change turboboost speed , but not the power level settings.

Then I saw something about TDP throttling with 8250u, 8550u on different laptops, so I did some google and finally changed the performance mode to have better CPU(almost the same with win10) & GPU(slightly better than before).
[Here's the result](https://imgur.com/LQbSqLI) 

I only change "Configurable TDP Boot Mode" & "1~4-Core Ratio Limit Override", [this](https://imgur.com/A29WzjY) is the TDP setting in BIOS which is hidden. I set it from 0x00(Nominal) to 0x02(Up). 

Performance on windows doesn't change too much so I guess some software or framework can override/ignore some settings in BIOS.

** You need to extract your own BIOS file and research it(in "user interface" section) because the BIOS variable offset is usually different on different devices.

**Comment by dkkyeremateng** [comment]
@businessman9 can you please help with your clover folder? I am unable to install Mojave on my i5-8250U

**Comment by 13xps** [comment]
@businessman9 

Can you please link to the guide that you followed to extract the bios? 

Also, I am a little confused. Is "Configurable TDP Boot Mode" & "1~4-Core Ratio Limit Override" one setting or two? Because after you only list one setting you changed: "0x00(Nominal) to 0x02(Up)"

So is there two settings we need to change, or just one?  Thanks

**Comment by businessman9** [comment]
No , CPU MSR settings are not necessary, I only set the BIOS.

n-Core Ratio Limit Override are 4 different settings of clock speed from 1 to 4 cores, I think it’ll be fine if those setting remain original.

**Comment by 13xps** [comment]
@businessman9 Thanks for the reply. OK, I changed Configurable TDP Boot Mode but I did not notice a difference in CPU behavior. Damn, any other ideas? What values do you have for 1~4-Core Ratio Limit Override?

**Comment by the-darkvoid** [comment]
@13xps , @businessman9 : Any update / progress on this from either of you?

**Comment by businessman9** [comment]
So far I can't get any other solution for this problem, I'm sorry.

**Comment by vichaos** [comment]
Set TDP Boot Mode to 0x02 seem to improve the performance on i7-8550u

### Intel Power Gadget (idle)
[https://imgur.com/q0MflF6](url)
### Geekbench
[https://imgur.com/ywSfAep](url)
### Cinebench 
[https://imgur.com/cDDTXMP](url)

**Comment by egore24** [comment]
vichaos, thank you for the comment...how does on set the TDP boot mode to 0x02 on the 9360? Thanks!

**Comment by wanghuangjie** [comment]
> Set TDP Boot Mode to 0x02 seem to improve the performance on i7-8550u
> 
> ### Intel Power Gadget (idle)
> https://imgur.com/q0MflF6
> 
> ### Geekbench
> https://imgur.com/ywSfAep
> 
> ### Cinebench
> https://imgur.com/rNnFB9Y
> 
> ### Cinebench (w/o undervolt)
> https://imgur.com/FjIY6uA

thx for share
i've change tdp boot mode to 0x02 by setup_var 0x4DF 0x02.
and it works, while running luxmark, load keeps above 25W.

But the performance still diff from your result. Especially in gpu performance ,lower more than 30%.
![9228277C2ECD13C9C5526D9B8232B45E](https://user-images.githubusercontent.com/3711191/60425817-f0409c80-9c25-11e9-934c-343a364f1787.jpg)

it there anything need to change?

**Comment by vichaos** [comment]
> > Set TDP Boot Mode to 0x02 seem to improve the performance on i7-8550u
> > ### Intel Power Gadget (idle)
> > https://imgur.com/q0MflF6
> > ### Geekbench
> > https://imgur.com/ywSfAep
> > ### Cinebench
> > https://imgur.com/rNnFB9Y
> > ### Cinebench (w/o undervolt)
> > https://imgur.com/FjIY6uA
> 
> thx for share
> i've change tdp boot mode to 0x02 by **setup_var 0x4DF 0x02.**
> and it works, while running luxmark, load keeps above 20W.
> ![536E9884D8E13B49533222601883ECB8](https://user-images.githubusercontent.com/3711191/60427070-8675c200-9c28-11e9-97d9-2cbcafc5d325.jpg)
> 
> But the performance still diff from your result. Especially in gpu performance ,lower more than 30% compare to your score.
> ![9228277C2ECD13C9C5526D9B8232B45E](https://user-images.githubusercontent.com/3711191/60425817-f0409c80-9c25-11e9-934c-343a364f1787.jpg)
> 
> it there anything need to change?

From your result I guess it just your machine got thermal throttling faster than mine. When I'm running Geekbench Compute benchmark the temperature on my machine is moving in a range between 40c-58c.

I don't expect much from HD620 but here are luxmark(GPU) and Cinebench R15 score. 
<img width="1600" alt="Screen Shot 2562-07-02 at 00 16 36" src="https://user-images.githubusercontent.com/724055/60455174-f7849c00-9c5f-11e9-914a-17c85ad6857b.png">
<img width="1600" alt="Screen Shot 2562-07-02 at 00 40 14" src="https://user-images.githubusercontent.com/724055/60455961-17b55a80-9c62-11e9-9968-da8e1f9725b1.png">

Other settings that might/might not effecting the score
1. SpeedStep disable  
2. SpeedShift enable 
3. UnderVolt 140,50 *This might be working on my machine only 
4. Balance Performance - https://github.com/stevezhengshiqi/one-key-cpufriend. actually performance profile is giving better result with a cost of power consumption 

All above setting the Intel Power Gadget is reporting 1.79w-1.91w, 40c during idle state.

**Comment by aCaiMaster** [comment]
> > > Set TDP Boot Mode to 0x02 seem to improve the performance on i7-8550u
> > > ### Intel Power Gadget (idle)
> > > https://imgur.com/q0MflF6
> > > ### Geekbench
> > > https://imgur.com/ywSfAep
> > > ### Cinebench
> > > https://imgur.com/rNnFB9Y
> > > ### Cinebench (w/o undervolt)
> > > https://imgur.com/FjIY6uA
> > 
> > 
> > thx for share
> > i've change tdp boot mode to 0x02 by **setup_var 0x4DF 0x02.**
> > and it works, while running luxmark, load keeps above 20W.
> > ![536E9884D8E13B49533222601883ECB8](https://user-images.githubusercontent.com/3711191/60427070-8675c200-9c28-11e9-97d9-2cbcafc5d325.jpg)
> > But the performance still diff from your result. Especially in gpu performance ,lower more than 30% compare to your score.
> > ![9228277C2ECD13C9C5526D9B8232B45E](https://user-images.githubusercontent.com/3711191/60425817-f0409c80-9c25-11e9-934c-343a364f1787.jpg)
> > it there anything need to change?
> 
> From your result I guess it just your machine got thermal throttling faster than mine. When I'm running Geekbench Compute benchmark the temperature on my machine is moving in a range between 40c-58c.
> 
> I don't expect much from HD620 but here are luxmark(GPU) and Cinebench R15 score.
> <img alt="Screen Shot 2562-07-02 at 00 16 36" width="1600" src="https://user-images.githubusercontent.com/724055/60455174-f7849c00-9c5f-11e9-914a-17c85ad6857b.png">
> <img alt="Screen Shot 2562-07-02 at 00 40 14" width="1600" src="https://user-images.githubusercontent.com/724055/60455961-17b55a80-9c62-11e9-9968-da8e1f9725b1.png">
> 
> Other settings that might/might not effecting the score
> 
> 1. SpeedStep disable
> 2. SpeedShift enable
> 3. UnderVolt 140,50 *This might be working on my machine only
> 4. Balance Performance - https://github.com/stevezhengshiqi/one-key-cpufriend. actually performance profile is giving better result with a cost of power consumption
> 
> All above setting the Intel Power Gadget is reporting 1.79w-1.91w, 40c during idle state.

On UnderVolt。 how do you operate?  I know i can use XTU under Windows. But how to operate under MacOS？ Modify BIOS？ like ‘setup_var 0x4DF 0x02’  this？ Use DVMT.efi？      thanks.

**Comment by wanghuangjie** [comment]
@vichaos 
i just wanna say thank you!

with tdp boot mode to 0x02 . my xps is able to carry 4k screen for daily use.
the only downside is cpu temperature can goes up to 100degree ,
so the external fan is needed.

you save my xps.
thank you !

**Comment by vichaos** [comment]
@wanghuangjie Just apply thermal pad in between heatpipe and backplate following this guide. 

https://www.reddit.com/r/Dell/comments/6gnfbv/easy_massive_thermal_improvements_on_dell_xps_13/
![thermalpad](https://user-images.githubusercontent.com/724055/61125605-784f5d80-a4d4-11e9-9092-8d1431b9260d.jpg)

Just to make sure that there is no air gap between thermal pad and backplate even though the result will be worse.

**Comment by wanghuangjie** [comment]
@vichaos 

perfect！
thank you！

![image](https://user-images.githubusercontent.com/3711191/61178715-16ead400-a625-11e9-81d2-4ffc7b0de0de.png)

**Comment by vichaos** [comment]
@wanghuangjie from your result I have noticed one thing that look really odd. When the turbo boost is dragging up the frequency of **all** cpu cores to **3.7Ghz**. I think the power consumption should be **above** 20-25watt. 

<img width="843" alt="Screen Shot 2562-07-17 at 03 04 10" src="https://user-images.githubusercontent.com/724055/61326394-d8c9fc00-a840-11e9-91af-0548b6ab88e7.png">

Here is my clover folder If anyone interested.
[clover.zip](https://github.com/the-darkvoid/XPS9360-macOS/files/3399088/clover.zip)

TDP modes:
- setup_var 0x4DF 0x00  (default)
- setup_var 0x4DF 0x01  (battery life)
- setup_var 0x4DF 0x02  (performance) *if someone really serious about the battery life I recommend https://github.com/rugarciap/Turbo-Boost-Switcher so you don't need to keep changing this value.  

<img width="1712" alt="Screen Shot 2562-07-17 at 04 00 09" src="https://user-images.githubusercontent.com/724055/61329444-8213f080-a847-11e9-826b-ff46465b89b5.png">

**Comment by vichaos** [comment]
@the-darkvoid I think this issue should have been solved now. Comparing my score on mojave(10.14.5) with @businessman9 (win10 [score](https://imgur.com/LQbSqLI)). the results are not much difference at all. I think it just the CPUFriendDataProvider.kext that matter but please recheck with my [clover](https://github.com/the-darkvoid/XPS9360-macOS/files/3399088/clover.zip). 

**XPS-9360 QHD i7-8550U, BIOS 2.11.0, Mojave(10.14.5), Clover r4988**
<img width="1600" alt="Screen Shot 2562-07-17 at 04 51 33" src="https://user-images.githubusercontent.com/724055/61332621-e8e8d800-a84e-11e9-86fc-280b4b81da3c.png">


> It turns out that Dell sets a TDP limit in BIOS.
> I read [this](https://www.reddit.com/r/macbookpro/comments/91256u/optimal_cpu_tuning_settings_for_i9_mbp_to_stop/) about VRM throttling and tried to edit CPU MSR settings. I was able to change turboboost speed , but not the power level settings.
> 
> Then I saw something about TDP throttling with 8250u, 8550u on different laptops, so I did some google and finally changed the performance mode to have better CPU(almost the same with win10) & GPU(slightly better than before).
> [Here's the result](https://imgur.com/LQbSqLI)
> 
> I only change "Configurable TDP Boot Mode" & "1~4-Core Ratio Limit Override", [this](https://imgur.com/A29WzjY) is the TDP setting in BIOS which is hidden. I set it from 0x00(Nominal) to 0x02(Up).
> 
> Performance on windows doesn't change too much so I guess some software or framework can override/ignore some settings in BIOS.
> 
> ** You need to extract your own BIOS file and research it(in "user interface" section) because the BIOS variable offset is usually different on different devices.
> 
> ** I use DVMT.efi setup_var to change the values.

**Comment by the-darkvoid** [comment]
@vichaos & @wanghuangjie,

Thank you for doing in-depth research on this. It would be interesting to see if it can be done without changes in the bios like it works on Windows.

Is the previously mentioned Turbo-Boost-Switcher perhaps able to achieve that? Did anyone test?

**Comment by vichaos** [comment]
I have some script for reading/modifying the values in Model-Specific Registers  but since my machine didn't have any issue with throttling so I'm not quite sure about the result.

<img width="1600" alt="Screen Shot 2562-07-17 at 19 54 54" src="https://user-images.githubusercontent.com/724055/61377865-43754900-a8ce-11e9-8f53-57d1118935f7.png">

0x610.py is for explaining Package power limits hexcode 
msr-init.sh is for applying changes 

**Try this if you are having throttling issue**
`./msr-init.sh 0x428198001B80C8 0x1e1e1e1e`

 0x428198001B80C8 -> Set pkg_clamping_limit_2 to false, increase pl1 to 25, and reduce 'pkg_power_limit_time_window_1' to 8s. [1]

0x1e1e1e1e -> Lower Turbo Boost for 4/3/2/1 cores to 3GHz. [2]

**All necessary files are in here** 
[voltageshift+scrips.zip](https://github.com/the-darkvoid/XPS9360-macOS/files/3401983/voltageshift%2Bscrips.zip)

**For references** 
[1] https://www.kitguru.net/lifestyle/mobile/apple/matthew-wilson/macbook-pro-2018-throttling-fix/
[2] https://gist.github.com/Mnkai/5a8edd34bd949199224b33bd90b8c3d4

**Comment by the-darkvoid** [comment]
@vichaos your reply seems to close the issue for those who want to do it in OS X. Thanks for that!
Since no-one posted any testing reports closing this for now.
