### ISSUE TITLE
Clover files not working with the i5-8250U with FHD

### ISSUE THREAD

**Issue by dkkyeremateng** [the-darkvoid/XPS9360-macOS#101]
I'm unable to boot High Sierra with your files.

**Comment by dkkyeremateng** [comment]
I was able to boot High Sierra when I replace your config.plist with the config_HD615_620_630_640_650.plist from RehabMan. Do I need to change something in your config for it works?

**Comment by dkkyeremateng** [comment]
Finally have everything working on 10.13.5
I had to change my DVMT to 0x03 but still can't boot 10.14 installer to boot.

**Comment by the-darkvoid** [comment]
@dkkyeremateng: I don't have your configuration, but the users in the forum thread on tonymac do and might be able to help you.
