### ISSUE TITLE
Mojave - There is sound, no Microphone

### ISSUE THREAD

**Issue by lega2013** [the-darkvoid/XPS9360-macOS#102]
Use ./XPS9360.sh --patch-hda，Mojave - There is sound, no Microphone，Newly installed Mojave10.14.2

**Comment by 13xps** [comment]
See if this helps:  https://github.com/the-darkvoid/XPS9360-macOS/issues/85

I used AppleALC.kext and then added "alcid=11" in boot arguments in clover configurator to get it to work.

**Comment by lega2013** [comment]
> 看看这是否有帮助： [＃85](https://github.com/the-darkvoid/XPS9360-macOS/issues/85)
> 
> 我使用了AppleALC.kext，然后在三叶草配置器中的引导参数中添加了“alcid = 11”以使其工作。
> 
> 另外，我不确定这有多重要，但是我发现在EFI / CLOVER / kexts /其他所有kext与L / E配合使用这个回购更好。（当然这个名为“Library-Extensions”的回购邮件在L / E中）

"Boot parameters" is added where, please say where to add.“Acpi","Boot"or"Boot Graphics"... Thank you.

**Comment by lega2013** [comment]
> 启动，然后自定义标志框。请参见附图。确保alcid = 11和前一个条目之间有空格。忘记图片中的第5步，保存！大声笑
> <img alt="屏幕截图2018-12-10于10 19 14 14" width="703" src="https://user-images.githubusercontent.com/42802126/49707321-c2820f00-fc65-11e8-9740-91492add65e4.png">

Successful. Thank you. I used AppleALC.kext and added "alcid = 11" to the boot parameters  to make it work.
