### ISSUE TITLE
slow boot time with your new files

### ISSUE THREAD

**Issue by dkkyeremateng** [the-darkvoid/XPS9360-macOS#106]
I'm getting a slow boot time with the new files on 10.13.5

**Comment by johncronan** [comment]
I also have this issue. Message in verbose boot is:

`AppleIntelLpssI2CController::_serviceMatchingTimeSubr: fTimerServiceMatching timed out, fNotifications 0
AppleIntelLpssI2CController::_serviceMatchingTimeSubr: fTimerServiceMatching timed out, fNotifications 0
kextd stall[0], (60s): 'SMCSMBusController`

It doesn't occur with VirtualSMC in EFI/CLOVER/kexts. Once I install that to System/Library/Extensions the slow boot starts.

**Comment by johncronan** [comment]
Switching to FakeSMC from VirtualSMC fixes the issue for me.

**Comment by the-darkvoid** [comment]
Latest git makes use of VirtualSMC.
