### ISSUE TITLE
USB 3 device in USB C port doesn't work (but there is a workaround)

### ISSUE THREAD

**Issue by johncronan** [the-darkvoid/XPS9360-macOS#108]
I've installed 10.13.6 using your config.plist, ACPI patches, and all kexts installed to /S/L/E (with the addition of LiluFriend). I mention that last part because, if you don't also experience this particular issue, perhaps it is because of kexts in EFI/CLOVER, I dunno. (The only other changes I have are the graphics fixes for HD 630, as this one is an i7-7560u.)

The issue is, a USB 3 flash drive in the USB C port doesn't work. Nothing appears.

I discovered a workaround, though: if I put the laptop to sleep, then wake it with the flash drive inserted in that port, it starts working normally. Meaning that I can eject, reinsert, and it all works normally. If the computer sleeps again, I have to repeat this, however.

Which behavior do you see on your hack? Thanks!

**Comment by asinggih** [comment]
> I've installed 10.13.6 using your config.plist, ACPI patches, and all kexts installed to /S/L/E (with the addition of LiluFriend). I mention that last part because, if you don't also experience this particular issue, perhaps it is because of kexts in EFI/CLOVER, I dunno. (The only other changes I have are the graphics fixes for HD 630, as this one is an i7-7560u.)
> 
> The issue is, a USB 3 flash drive in the USB C port doesn't work. Nothing appears.
> 
> I discovered a workaround, though: if I put the laptop to sleep, then wake it with the flash drive inserted in that port, it starts working normally. Meaning that I can eject, reinsert, and it all works normally. If the computer sleeps again, I have to repeat this, however.
> 
> Which behavior do you see on your hack? Thanks!

I also have the same behaviour as yours. Plugging in my USB-C into the laptop, in the middle of the sleep gives me a proper functionality of the USB-C

**Comment by the-darkvoid** [comment]
At the moment there is no known work around either than plugging in the device during sleep or before startup. 

Forcing the thunderbolt chip to be permanently on in the bios using Thunderbolt ForcePower does not yield positive results either.
