### ISSUE TITLE
No mic with AppleHDA_ALC256.kext

### ISSUE THREAD

**Issue by dkkyeremateng** [the-darkvoid/XPS9360-macOS#109]
No mic with AppleHDA_ALC256.kext

**Comment by mpross512** [comment]
Try using Apple_ALC.kext instead with the clover boot args `alcid=11`

**Comment by egore24** [comment]
Or alcid=56

**Comment by the-darkvoid** [comment]
Using `alcid=56` (`DalianSkyRealtek ALC256 (3246) for Dell Series`), I noticed that this only gives Line Out, no microphone.

`alcid=11` (`Rockjesus - Realtek ALC256 (3246) - dell 7559`) gives microphone output and might be the better choice.

Note that the codec information for the Dell 7559 looks to be an identical chipset to the XPS 9360.

I haven't tested layout 11 in detail yet, but I am planning to build a HDA injector with it to see how well it performs.

**Comment by iarnihc** [comment]
Hi～
You can click this link：[https://github.com/hackintosh-stuff/ComboJack](url)

**Comment by dkkyeremateng** [comment]
> Using `alcid=56` (`DalianSkyRealtek ALC256 (3246) for Dell Series`), I noticed that this only gives Line Out, no microphone.
> 
> `alcid=11` (`Rockjesus - Realtek ALC256 (3246) - dell 7559`) gives microphone output and might be the better choice.
> 
> Note that the codec information for the Dell 7559 looks to be an identical chipset to the XPS 9360.
> 
> I haven't tested layout 11 in detail yet, but I am planning to build a HDA injector with it to see how well it performs.

Sound and mic now working with AppleALC.kext and alcid=11

**Comment by Mateo1234454545** [comment]
Even after waking from sleep ?

**Comment by mpross512** [comment]
Indeed, `alcid=11` works even after waking from sleep!

**Comment by Mateo1234454545** [comment]
But you still need ssdt for alc256 and codeccommander ? Is that right ?

**Comment by dkkyeremateng** [comment]
> But you still need ssdt for alc256 and codeccommander ? Is that right ?

Yes you need that.

**Comment by the-darkvoid** [comment]
> But you still need ssdt for alc256 and codeccommander ? Is that right ?

You shouldn't need either. Test it out (and ensure to rebuild your cache with kext util).

**Comment by egore24** [comment]
> > But you still need ssdt for alc256 and codeccommander ? Is that right ?
> 
> You shouldn't need either. Test it out (and ensure to rebuild your cache with kext util).

Confirmed. alc256 SSDT removed and no CC. Sound works as expected.
