### ISSUE TITLE
SSDT-TBFP.aml？I did not find this file

### ISSUE THREAD

**Issue by hoanX** [the-darkvoid/XPS9360-macOS#11]
There is an SSDT-TBFP.aml file in the config.plist, but it is not found in the DSDT folder,This is repair Thunderbolt hotplug?
I use your IOElectrify.kext does not work well, such as my phone can only charge can not transfer data

**Comment by the-darkvoid** [comment]
@hoanX, the current repository uses the PCI-Express method. SSDT-TBFP is no longer needed.
