### ISSUE TITLE
Enable Touchscreen

### ISSUE THREAD

**Issue by jordangarside** [the-darkvoid/XPS9360-macOS#111]
Hi there,

I was just wondering how I go about enabling the touchscreen display.

Thanks!

**Comment by egore24** [comment]
It’s should be enabled with this repo. Do you have it enabled in BIOS?

**Comment by jordangarside** [comment]
@egore24 Yup, it's enabled in the BIOS. It was working for me on macOS before copying everything over from the clover folder.

**Comment by jordangarside** [comment]
Worked after reboot and making sure BIOS settings were all correct (touchscreen was enabled though).

**Comment by the-darkvoid** [comment]
To be honest, I have mine off to save battery. Its not that useful in macOS, besides showing MacBook Pro users how your hacktop is better than their laptop... (and it prevents finger prints)
