### ISSUE TITLE
My CPUFriendDataProvider.kext allows idle down to 0.6GHZ

### ISSUE THREAD

**Issue by egore24** [the-darkvoid/XPS9360-macOS#113]
[CPUFriendDataProvider.kext.zip](https://github.com/the-darkvoid/XPS9360-macOS/files/2818526/CPUFriendDataProvider.kext.zip)
Hello DV. I have made a CPUFriendDataProvider.kext from the MacBookPro15,2.plist which is consistently providing a lower idle speed than the one you are providing. I've attached it here. That being said, I a pretty sure I made it with the correct parameters. Take a look and let me know what you think. 

P.S. I was only able to achieve 1.2GHZ idle with your kext.

Thanks much!

**Comment by dkkyeremateng** [comment]
i5 or i7 model?

**Comment by Mateo1234454545** [comment]
That's what I thought.
In my opinion it doesn't make sense to use it.

**Comment by the-darkvoid** [comment]
@egore24 is just matching the Windows behaviour, I don't see anything wrong with that, so I've merged the change.
