### ISSUE TITLE
Using the new AppleALC layout 11, Speaker and headphone noise is serious 

### ISSUE THREAD

**Issue by WentaoRen** [the-darkvoid/XPS9360-macOS#114]
Using the new AppleALC layout 11, Speaker and headphone noise becomes very serious.
Today I covered my computer clover directory with the latest clover from you. But I found the noise becomes very serious.

**Comment by WentaoRen** [comment]
> Not sure what 'serious noise' means. Did you try and reset any volume nvram settings?

How to reset volume nvram settings on this laptop？

**Comment by Mateo1234454545** [comment]
> Not sure what 'serious noise' means. Did you try and reset any volume nvram settings?

He means a high pitch noise , happens to me also. It happens randomly and makes cpu load to 40-50%. Only way to stop this is to reboot.

**Comment by the-darkvoid** [comment]
Both on speaker and headphones? Also without using headphones at all?

Did you remove CodecCommander.kext from /L/E and rebuild kext cache?

**Comment by WentaoRen** [comment]
> Both on speaker and headphones? Also without using headphones at all?
> 
> Did you remove CodecCommander.kext from /L/E and rebuild kext cache?

No，I try it later. But I tried  to turn down the volume and let the speak mute, Also I can hear current sound.

**Comment by Mateo1234454545** [comment]
Noise is only from speakers , no codeccommander or ssdt for alc. Rebuilded kexts as I should.

**Comment by Chilluminati91** [comment]
Same problem, almost sounds like an old spinning harddrive. This occurs ocasionally and lasts a few minutes. Extremely obvious when scrolling through a website.

**Comment by the-darkvoid** [comment]
That would be coil whine. Did you try layout 0x0d instead?

**Comment by Chilluminati91** [comment]
Tried that out just now. Same problem. Can not test in Windows but it would be surprising if my XPS just suddenly started having extreme coil whine. Will revert back to my old backup and see if the problem persists.

**Comment by johann7gh** [comment]
Just updated to Darkvoid's latest repo with AppleALC with layout 11, I too am experiencing really poor quality headphone output.  Very static-filled, and sounds like an overdriven speaker.  Normal speakers sound fine, and a USB audio sound card works normally as well.

**Comment by the-darkvoid** [comment]
I've been using the ComboJack solution mentioned in the other related issue.
Give that a try to see how the affects the sound quality?

**Comment by WentaoRen** [comment]
The noise still exsits,and the headphone doesn't work.

**Comment by the-darkvoid** [comment]
Only thing I can suggest is changing to layout 56 or 13. You could look into combining the layout 11 information with layout 56 to fix the microphone.

I'm using layout 11 in combination with a Bose QC35 headset using wire and not experiencing any issues.

**Comment by Chilluminati91** [comment]
layout 13 in combination with a manual combojack install seems to have fixed the coil whine.

**Comment by WentaoRen** [comment]
> layout 13 in combination with a manual combojack install seems to have fixed the coil whine.

how to do？

**Comment by Chilluminati91** [comment]
> > layout 13 in combination with a manual combojack install seems to have fixed the coil whine.
> 
> how to do？

1. Download the repo, and open /XPS9360-macOS-master/DSDT/SSDT-Config.dsl
2. Replace the AUDL section with "Name(AUDL, 0x0D)", save and close
3. sudo XPS9360.sh --compile-dsdt (just like always)
4. Copy /XPS9360-macOS-master/CLOVER/ACPI/patched/SSDT-Config.aml to the corresponding folder on your EFI partition
5. Reboot, install the previously discussed combojack, reboot again

**Comment by the-darkvoid** [comment]
@WentaoRen,

VerbStub.kext is already included in the repository. I plan to reach out to the ComboJack author to make ComboJack use CodecCommander.kext instead, which already supports receiving verb commands from user space.

This would allow using both CodecCommander and ComboJack functionality at the same time (if required).

**Comment by rama1981** [comment]
my config 9360-4k-i7-7500U 
my coilwhine finally gone when I changed my layout-id to 56 = in SSDT_config to 0x38.
Thank you for your ideas.

**Comment by WentaoRen** [comment]
> @WentaoRen,
> 
> VerbStub.kext (required for ComboJack) is already included in the repository. I plan to reach out to the ComboJack author to make ComboJack use CodecCommander.kext instead, which already supports receiving verb commands from user space.
> 
> This would allow using both CodecCommander and ComboJack functionality at the same time (if required).

thanks, now speaker and headphone both work fine!  谢谢！It’s mean “thanks” in Chinese.

**Comment by WentaoRen** [comment]
> > > layout 13 in combination with a manual combojack install seems to have fixed the coil whine.
> > 
> > 
> > how to do？
> 
> 1. Download the repo, and open /XPS9360-macOS-master/DSDT/SSDT-Config.dsl
> 2. Replace the AUDL section with "Name(AUDL, 0x0D)", save and close
> 3. sudo XPS9360.sh --compile-dsdt (just like always)
> 4. Copy /XPS9360-macOS-master/CLOVER/ACPI/patched/SSDT-Config.aml to the corresponding folder on your EFI partition
> 5. Reboot, install the previously discussed combojack, reboot again

Thank you very much！now both of them works well！非常感谢！

**Comment by the-darkvoid** [comment]
The latest commit reverts to 0x0D as default audio layout, specifically due to issues experienced by the i7-7500U users. 

It also adds ComboJack as a user application to address headphone and headset connectivity.

**Comment by WentaoRen** [comment]
thanks!
