### ISSUE TITLE
Headphone not working properly in latest update.

### ISSUE THREAD

**Issue by magneticchen** [the-darkvoid/XPS9360-macOS#115]
In previous version I can use AppleALC by changing dsdt audio value to 0x0b. But in the recent version with macos 1.14.3. I can't hear any voice from headphone port. And I've installed codecommander and rebuilt kext caches for the new update.

**Comment by shwiseman** [comment]
Can confirm this issue is present.

**Comment by the-darkvoid** [comment]
@shwiseman: Whats the build number of the latest version you are both referring to?
Is this the 10.14.3 Supplemental Update or 10.14.3 plain.

**Comment by shwiseman** [comment]
@the-darkvoid I believe plain. The computer only lists "10.14.3" as the version.

**Comment by Chilluminati91** [comment]
Can confirm, headphone jack is not working properly in the latest build. The sound is very quite and the volume change sound is garbled and cracks.

**Comment by magneticchen** [comment]
> @shwiseman: Whats the build number of the latest version you are both referring to?
> Is this the 10.14.3 Supplemental Update or 10.14.3 plain.

the build number is 18D109

**Comment by magneticchen** [comment]
I am wondering that it is not macos version that matters. Maybe it is new clover setup causes the problems.

**Comment by the-darkvoid** [comment]
Tested this against build 18D109. Headset is working as expected.

Note that I do not have CodecCommander.kext installed at all. If you use AppleALC with 0x0b layout, you don't need CodecCommander.kext in /L/E.

Remove CodecCommander.kext and any left-over AppleALC256.kext from /LE and rebuild kext cache.

**Comment by magneticchen** [comment]
> Tested this against build 18D109. Headset is working as expected.
> 
> Note that I do not have CodecCommander.kext installed at all. If you use AppleALC with 0x0b layout, you don't need CodecCommander.kext in /L/E.
> 
> Remove CodecCommander.kext and any left-over AppleALC256.kext from /LE and rebuild kext cache.

I have done what you said. Removing CodecCommander and rebuilding the cache with layout 0x0b and AppleALC. The change is that now internal speaker working, but has no good luck on the headphone jack, it is now with a uncleared glitched sound. BTW in your previous commits. I literally forgot to remove CodecCommander but AppleALC still works. Just a mention. Thanks for your effort!

**Comment by SheldonPeng** [comment]
> > 针对build 18D109进行了测试。耳机按预期工作。
> > 请注意，我根本没有安装CodecCommander.kext。如果您使用具有0x0b布局的AppleALC，则在/ L / E中不需要CodecCommander.kext。
> > 从/ LE删除CodecCommander.kext和任何剩余的AppleALC256.kext并重建kext缓存。
> 
> 我做了你说的话。删除CodecCommander并使用布局0x0b和AppleALC重建缓存。改变的是，现在内部扬声器工作，但耳机插孔没有好运，它现在有一个未清除的闪烁声音。BTW在您之前的提交中。我真的忘了删除CodecCommander，但AppleALC仍然有效。只是提一下。谢谢你的努力！

Hello，last night i was reinstalled my system and i had the same problems；However, I find a solution and I have solved this problems. I hope this will help you.         
https://github.com/hackintosh-stuff/ComboJack

**Comment by j3ko** [comment]
> > > 针对build 18D109进行了测试。耳机按预期工作。
> > > 请注意，我根本没有安装CodecCommander.kext。如果您使用具有0x0b布局的AppleALC，则在/ L / E中不需要CodecCommander.kext。
> > > 从/ LE删除CodecCommander.kext和任何剩余的AppleALC256.kext并重建kext缓存。
> > 
> > 
> > 我做了你说的话。删除CodecCommander并使用布局0x0b和AppleALC重建缓存。改变的是，现在内部扬声器工作，但耳机插孔没有好运，它现在有一个未清除的闪烁声音。BTW在您之前的提交中。我真的忘了删除CodecCommander，但AppleALC仍然有效。只是提一下。谢谢你的努力！
> 
> Hello，last night i was reinstalled my system and i had the same problems；However, I find a solution and I have solved this problems. I hope this will help you.
> https://github.com/hackintosh-stuff/ComboJack

This fixed it for me, headphones work now

**Comment by shwiseman** [comment]
Mine still do not. i7-7500U

**Comment by j3ko** [comment]
> Mine still do not. i7-7500U

I'm not sure if it is necessary but in the AppleALC commit (db5ffed175fc767d7d218d8a1ccfa471bd6cd4de) there were other changes to the repo, especially in /Clover/ACPI/patched

**Comment by syifan** [comment]
@magneticchen I think the macos version does not matter. I have not upgraded to 10.14.3 and I am still having the same issue. I am using 10.14.2 now.

**Comment by syifan** [comment]
> > > 针对build 18D109进行了测试。耳机按预期工作。
> > > 请注意，我根本没有安装CodecCommander.kext。如果您使用具有0x0b布局的AppleALC，则在/ L / E中不需要CodecCommander.kext。
> > > 从/ LE删除CodecCommander.kext和任何剩余的AppleALC256.kext并重建kext缓存。
> > 
> > 
> > 我做了你说的话。删除CodecCommander并使用布局0x0b和AppleALC重建缓存。改变的是，现在内部扬声器工作，但耳机插孔没有好运，它现在有一个未清除的闪烁声音。BTW在您之前的提交中。我真的忘了删除CodecCommander，但AppleALC仍然有效。只是提一下。谢谢你的努力！
> 
> Hello，last night i was reinstalled my system and i had the same problems；However, I find a solution and I have solved this problems. I hope this will help you.
> https://github.com/hackintosh-stuff/ComboJack

This solution worked for me. I have to put the kext file in /EFI/EFI/clover/kext/others folder. It would not work it the kext is put in /L/E.

**Comment by SheldonPeng** [comment]
> 我还是没有。i7-7500U

Hello,I thing maybe this kext will help you to solve the problem.
You can put it in CLOVER/kexts/others and you need to delete original kext.
I hope it will help you.
[Uploading AppleALC.kext.zip…]()

**Comment by syifan** [comment]
> Mine still do not. i7-7500U

Mine is i7-7200u. Can it make a difference?

**Comment by egore24** [comment]
Can confirm this issue persists. Completely fresh install of Mojave 10.14.3 (18D109) with latest repo. ComboJack does however correct the issue. Would be a plus if CJ wasn't needed. Thanks.

**Comment by magneticchen** [comment]
> > > 针对build 18D109进行了测试。耳机按预期工作。
> > > 请注意，我根本没有安装CodecCommander.kext。如果您使用具有0x0b布局的AppleALC，则在/ L / E中不需要CodecCommander.kext。
> > > 从/ LE删除CodecCommander.kext和任何剩余的AppleALC256.kext并重建kext缓存。
> > 
> > 
> > 我做了你说的话。删除CodecCommander并使用布局0x0b和AppleALC重建缓存。改变的是，现在内部扬声器工作，但耳机插孔没有好运，它现在有一个未清除的闪烁声音。BTW在您之前的提交中。我真的忘了删除CodecCommander，但AppleALC仍然有效。只是提一下。谢谢你的努力！
> 
> Hello，last night i was reinstalled my system and i had the same problems；However, I find a solution and I have solved this problems. I hope this will help you.
> https://github.com/hackintosh-stuff/ComboJack

Works for me.

**Comment by the-darkvoid** [comment]
Based on feedback VerbStub.kext was already present, however the repository setup script now also includes the ComboJack user daemon installation. This is in the latest commit.

When I have time I'll do a pull request against ComboJack to make it work with CodecCommander as well, which has had a hda-verb client extension since a number of years for these exact use cases.
This would eliminate the requirement of VerbStub.kext

**Comment by Andrw0830** [comment]
> Based on feedback VerbStub.kext was already present, however the repository setup script now also includes the ComboJack user daemon installation. This is in the latest commit.
> 
> When I have time I'll do a pull request against ComboJack to make it work with CodecCommander as well, which has had a hda-verb client extension since a number of years for these exact use cases.
> This would eliminate the requirement of VerbStub.kext

Thanks man! I have the same codec on my Dell Inspiron 7567 and hope we can get it to work with CodecCommander. This should mean easier for new OS versions since CodecCommander is more widely used.

**Comment by the-darkvoid** [comment]
Pull request was submitted to https://github.com/hackintosh-stuff/ComboJack/commit/a5fb1b9709bb9f2e4c711637214b233c1eaf8d85 and merged successfully.
