### ISSUE TITLE
About disable the sound when system boot up

### ISSUE THREAD

**Issue by n1ght2** [the-darkvoid/XPS9360-macOS#117]
I try mute the system volume before reboot but the sound is still there, that sound is a noise to me. I'm really want to disable that. It's there anyway to disable the boot sound?
I am truly grateful to your efforts, and sorry for my bad english.

**Comment by egore24** [comment]
Remove bootchimedxe.kext and audiodxe.kext from EFI/clover/drivers64uefi folder.

**Comment by n1ght2** [comment]
> Remove bootchimedxe.kext and audiodxe.kext from EFI/clover/drivers64uefi folder.

That worked! Thank you!

**Comment by koseduhemak** [comment]
Is there a way to change the volume? It is very loud...

**Comment by the-darkvoid** [comment]
There is an EFI executable in the tools folder to do that. Launch it using the EFI shell.

**Comment by WentaoRen** [comment]
> There is an EFI executable in the tools folder to do that. Launch it using the EFI shell.

which file？

**Comment by davefedele** [comment]
BootChimeCfg.efi
