### ISSUE TITLE
I notice that there is somebody has some problems about bluetooth

### ISSUE THREAD

**Issue by SheldonPeng** [the-darkvoid/XPS9360-macOS#119]
https://github.com/acidanthera/HibernationFixup
maybe this solution can help.

**Comment by SheldonPeng** [comment]
I can’t use Bluetooth when I wake up my computer if I use battery.But after I using this solution，my Bluetooth works normally

**Comment by jafd** [comment]
I'll try this. My problem with Bluetooth though is, lately, personal hotspot with an iPhone and Handoff/Continuity being hit and miss (at some point in the past, they've worked just fine)

**Comment by WentaoRen** [comment]
> https://github.com/acidanthera/HibernationFixup
> maybe this solution can help.

How Should I do？
