### ISSUE TITLE
Enable 4k resolution on external monitor?

### ISSUE THREAD

**Issue by filipdadgar** [the-darkvoid/XPS9360-macOS#122]
Darkvoid, thank you for all the effort.

[I opened same issue at hoanX/xps13-9360-i7-7560u]

I am using your repo  (and Hoans) for my rigg, everything works perfectly except getting resolutions above 1920x1080 for external monitor.

I have an external 4k TV connected through HDMI (tried DP as well), but cannot change the resolution to QHD.

Can you please guide me? (I managed to get the resolution by modifying the display plist file to higher but then the picture went all pink)

Regards,
Filip

**Comment by filipdadgar** [comment]
Okey, I might have something now. 

Used this site to generate a new DisplayId.plist: https://comsysto.github.io/Display-Override-PropertyList-File-Parser-and-Generator-with-HiDPI-Support-For-Scaled-Resolutions/

Then I installed RDM from http://avi.alkalay.net/software/RDM/

Can now manually from RDM change resolution without colors being all pink. :)

But surely there is something else I might be able to do in config.plist or a patch that takes care of this "natively" ?

**Comment by the-darkvoid** [comment]
There might be a problem with your screens EDID which Mac might have issues with.

Some more information can be found in the WhateverGreen.kext FAQ:
https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md
