### ISSUE TITLE
Will XPS 9360 capable to 4k output?

### ISSUE THREAD

**Issue by wanghuangjie** [the-darkvoid/XPS9360-macOS#123]
**First of all, huge thanks to DARKVOID,**

i'm using darkvoid's EFI with merely modify(like SN, boot driver name), and it's perfect ,IMHO.
but the problem is UHD620 is not capable, or 9360 is not capable for 4k output.

why am i saying this?

when using internal display ,everything work flawless.
But when i connect (type-c -> DP )  to 4k monitor(dell u2718q) ,using it for a while, it become lag.
FPS drops, cpu increase to 100%,(mainly chrome , kernel_task ,windowserver)

i've try to clean install Mojave, and try with different version  CPU FREIND, a usb fan to cooling .
Nothing change ,still lag after using it for a while.

wondering is there someone facing the same situation like me?
or maybe it's limitation of xps 9360?

Any reply will be appreciated.

 
![progress from idle to full load](https://user-images.githubusercontent.com/3711191/56888762-5f273b00-6aa7-11e9-95b4-1a21dc8d2561.png)

![Running luxmark,cpu drops down to 0.5Ghz ](https://user-images.githubusercontent.com/3711191/56904223-71699f00-6ad0-11e9-8fab-3fbc6927a307.png)

finally figure out ,
cpufriend is the key.

CPU AND GPU SHARE SAME POWER.

don't let cpu use too much power ,it will lead gpu short of power, hence gpu will become lag.

**Comment by wanghuangjie** [comment]
sorry duplicate issue.
ref: https://github.com/the-darkvoid/XPS9360-macOS/issues/100

**Comment by the-darkvoid** [comment]
The newly added OpenCore loader specifically enabled HDMI 2.0 support, this might resolve your issue.
I'll see about enabling it on Cover as well.

**Comment by wanghuangjie** [comment]
Seems like my issues has been solved since vram increase to 2048MB

[An iDiot's Guide To Lilu and its Plug-in's BY jaymonkey ](https://www.tonymacx86.com/threads/an-idiots-guide-to-lilu-and-its-plug-ins.260063/)

```                
                <key>framebuffer-patch-enable</key>
                <data>
                AQAAAA==
                </data>
                <key>framebuffer-unifiedmem</key>
                <data>
                AAAAgA==
                </data>
```

**Comment by wanghuangjie** [comment]
ckise

**Comment by wanghuangjie** [comment]
ref:https://github.com/the-darkvoid/XPS9360-macOS/issues/100
