### ISSUE TITLE
ComboJack malware? 

### ISSUE THREAD

**Issue by kcmark** [the-darkvoid/XPS9360-macOS#124]
Symantec Endpoint flagged ComboJack with the OSX.Malcol.2 malware. Probably a false positive but I thought I'd share it.

**Comment by the-darkvoid** [comment]
I've been looking to recompile ComboJack to talk to CodecCommander.
Lets see if that removes the virus flag.

**Comment by the-darkvoid** [comment]
@kcmark,

I've now updated ComboJack to support CodecCommander.kext and this recompiled version is no longer flagged as a virus.

The original version came from https://github.com/hackintosh-stuff/ComboJack directly, indeed suspicious its flagged.
