### ISSUE TITLE
Loss of keyboard brightness control

### ISSUE THREAD

**Issue by egore24** [the-darkvoid/XPS9360-macOS#125]
May 11 commit breaks keyboard brightness control (or possibly May 10 commit). No onscreen animation or brightness adjustments with actuation of brightness keys. Manual brightness is available and functional in the Displays Control Panel.

Thanks!

**Comment by the-darkvoid** [comment]
@egore24,

Missed to update a file from my local Clover. Commit e1bd21c should resolve this issue.

**Comment by egore24** [comment]
Confirmed this issue has been corrected. Keep up the excellent work!
