### ISSUE TITLE
Do you use windows 10 dual boot ?

### ISSUE THREAD

**Issue by x4080** [the-darkvoid/XPS9360-macOS#126]
Hi, I just replaced my wifi with dw1560 and  working nicely in mac os until I realized it's not working well in Windows 10

Do you use dual boot windows 10 ?

Thanks

**Comment by mpross512** [comment]
I do and it seems to be working alright for me. Did you install the windows drivers for it?

**Comment by businessman9** [comment]
As I know that there are different DW1560s, you can check your device ID and google it.

**Comment by x4080** [comment]
@mpross512 Yes I didnt do anything and windows already have driver in it, the problem that I have is slow and difficulty to connect to AP, but very good in mac

@businessman9, how to check the device ID ? And is it because of the windows driver ?

**Comment by the-darkvoid** [comment]
Closing this, because its not macOS related and no other answers were received.
