### ISSUE TITLE
No bluetooth after sleep

### ISSUE THREAD

**Issue by mpross512** [the-darkvoid/XPS9360-macOS#127]
Every time I wake up this laptop, the bluetooth has the wavy line through it and it's unavailable. 

When I was using `hibernatemode 25` it worked, but then every time I woke up my laptop I had to go back through the clover boot screen, and some applications I had open had to restart instead of remembering where I was at. 

Is there any way to have bluetooth after wake with `hibernatemode 3`? I've tried changing my timeouts in the clover config but it didn't seem to work for me.

**Comment by iarnihc** [comment]
If you are using the latest version of the EFI file from darkvoid.
You should check: 
config.plist/Boot: darkwake = 4 & selected NeverHibernate
brcmfirmwarerepo.kext and brcmpatchram2.kext exist in the lib/Extensions folder

If all of the above is true, please clean up kexts cache,
command line: sudo kextcache -i/
reboot, and good luck.

ps: my wireless card is DW1560, clover version:4920

**Comment by mpross512** [comment]
Unfortunately even after trying all those steps and making sure everything is in place, I still get the "Bluetooth Not Available" after closing my laptop lid, waiting for it to sleep, and then opening it again.

**Comment by mpross512** [comment]
Just a quick note, if my laptop goes to sleep while plugged in to power and then I wake it up, bluetooth is still functional. Bluetooth only gets disconnected after sleep while on battery power.

**Comment by davefedele** [comment]
I had the problem show up a few times until I cleaned my kexts. I had followed other guides which used a combination of dark-voids kexts from the `kexts` and `clover/kexts/other` folders.

Once I only used the ones from the `clover/kexts/other` folder I could properly sleep by closing the lid/choosing sleep via the apple menu/or using Alfred and bluetooth would work upon wake.

**Comment by mpross512** [comment]
I've actually just directly copied the clover folder from the github to my EFI folder, so it should be as clean as possible. Not exactly sure what's going on then.

**Comment by DaveFlowberries** [comment]
I have the same exact issue.

**Comment by bormanua** [comment]
Is there any solution for fixing this issue ?

**Comment by bormanua** [comment]
In my case Bluetooth works during 1-2 minutes after wake-up by lid open. But goes down after. When i wake up and use Bluetooth immediately  eg wireles headphones. They works fine until I stop the music. Then if laptop goes to sleep and I turn it back to life Bluetooth works again until it disappears from accesible devices after 1-2 minutes idle.

**Comment by imEgo** [comment]
I use https://github.com/Grid-H/OS-X-BrcmPatchRAM for over a month, Bluetooth works every time after sleep.

My card is DW1560

**Comment by the-darkvoid** [comment]
Closing based on @imEgo response.

**Comment by sebastian-ruiz** [comment]
I have applied the BrcmPatchRAM as suggested by @imEgo, and unchecked the three switches in the Bluetooth advanced settings. I still have the same problem with Bluetooth having a wiggly line through it after sleep.
