### ISSUE TITLE
10.14.5 compatibility

### ISSUE THREAD

**Issue by ElieMyIdea** [the-darkvoid/XPS9360-macOS#128]
Hi everyone,

Just want to know if you made 10.14.5 update without issue ?

Thank you 😀

**Comment by rocymp** [comment]
Just upgraded! Work well.

**Comment by ElieMyIdea** [comment]
Thanks 

⁣Télécharger BlueMail pour Android ​

Le 20 mai 2019 à 22:15, à 22:15, Roc Yang <notifications@github.com> a écrit:

**Comment by ElieMyIdea** [comment]
Everything's running smoothly

**Comment by ElieMyIdea** [comment]
Fix here (sorry) : #110
