### ISSUE TITLE
slow boot with ACPIBatteryManager.kext

### ISSUE THREAD

**Issue by davefedele** [the-darkvoid/XPS9360-macOS#129]
First off thanks for setting this repo up and continually sharing your updates.

If you have some way so we can buy you a beer or whatever please share a link.

I'm using your commits from yesterday e1bd21c (which were the latest at the time) with clover 4920 on a 9360 with the same specs as yours listed.

The boot is super slow (minutes long stall) when I have ACPIBatteryManager.kext in my `clover/kexts/other` folder.

When I remove `ACPIBatteryManager.kext` it boots in under 20seconds. Am I missing something?

I was confused that you have different kexts in the `kexts` folder vs the `clover/kexts/other` and copied all the files (not the s/l/e or the non-matching cpu kexts)into the `clover/kexts/others` folder.

Thanks for your help!

**Comment by adnbsr** [comment]
I am using `ACPIBatteryManager.kext` in */Library/Extensions* since it is not very important for boot and it is works perfectly but not updating percentage while charging (it is related to kext I suppose).

**Comment by the-darkvoid** [comment]
ACPIBatteryManager is now replaced by SMCBatteryManager (with VirtualSMC).
You have to run either, not both.

**Comment by davefedele** [comment]
Ok thank you for the reply, this was very helpful. So much in fact that I think it would be a good addition to the readme. I’ll prune my kexts now and consider this closed. 

Additionally, I own a Apple thunderbolt monitor and it was extremely gratifying to be able to use it with this setup; plugged in during sleep using a star tech adaptor (an authentic apple adaptor wouldn’t work)

**Comment by coletz** [comment]
> Note that `kexts` folder in the repository contains multiple approaches to run (i.e. `ACPIBatteryManager` vs `SMCBatteryManager`). While `clover/kexts/other` contains the suggested setup (usually the one I am running myself)

In my opinion it would be useful to leave this info in the readme
