### ISSUE TITLE
Typing causes cursor to freeze for 1 second

### ISSUE THREAD

**Issue by vephinx** [the-darkvoid/XPS9360-macOS#131]
The touchpad on its own works perfectly, the same goes for the keyboard.

The problem in combination with the keyboard: When a key on the keyboard is pressed, the cursor via the mousepad freezes for a second.

Example: type `cmd + space` while making circles using the touchpad.

The problem does not occur using a usb or bluetooth mouse. It only effects the touchpad.

NB: The problem occurs not only on the latest commit, but also on `ae05060`. I have not tried running older versions.

**Comment by the-darkvoid** [comment]
This function is on purpose, to prevent your palm from engaging the touchpad while typing.

You should be able to change the trackpad timeout based on keyboard input. 

To do that you need to edit Info.plist in VoodooI2CHID.kext:
![image](https://user-images.githubusercontent.com/10652482/58743663-86c94480-8453-11e9-969f-b6aa58e4ab4f.png)

Change QuietTimeAfterTyping to a value in milliseconds you are comfortable with, or simply 0 to disable it altogether.
