### ISSUE TITLE
When will MacOS 10.15 be suitable?THX ; )

### ISSUE THREAD

**Issue by ltesla** [the-darkvoid/XPS9360-macOS#132]

**Comment by the-darkvoid** [comment]
The beta came out only 8 hours ago. Generally I don't support running beta software on a hackintosh though. 

A hackintosh as such is already a non-supported platform and adding non-supported software on top of that as well is not suitable for a daily use machine.

I will only start looking at the adapting the repository once the release candidates are becoming available.
