### ISSUE TITLE
Test Combojack version

### ISSUE THREAD

**Issue by Andrw0830** [the-darkvoid/XPS9360-macOS#133]
Hello @the-darkvoid, I am trying to get people who have the Realtek ALC256 codec to test my ComboJack after I made a line change to make sure it doesn't interfere with other variants of the codec. @maz-1 asked if my patch is fine for all alc255/alc256 codecs so just wanted testers to see if it works and comment on my pull request. I just don't know who else or where else to ask. Here is my request:

https://github.com/hackintosh-stuff/ComboJack/pull/8

Thanks.

**Comment by the-darkvoid** [comment]
Sure, put a pull request against my copy of combojack and I'll test it on XPS 9360.

Need to lookup the specific codec type in my device, will get back on this.

**Comment by Andrw0830** [comment]
Thanks man! Pull request created. Will close this then.
