### ISSUE TITLE
Compatibility with 9360 KabyLake FHD

### ISSUE THREAD

**Issue by Sillyvan** [the-darkvoid/XPS9360-macOS#134]
Hey sorry for asking this here but how far is this compatible with a KabyLake FHD 9360?

I surely need another config.plist would i need anything else? 
hope someone can help here. we could add it to the readme if we can get this to work

Edit: I also know that i need DVMT Pre-allocation on 0x04 for FHD

**Comment by Richylitschy** [comment]
Take a look at the Tonymac forum. 

https://www.tonymacx86.com/threads/guide-dell-xps-13-9360-on-macos-sierra-10-12-x-lts-long-term-support-guide.213141/post-1966861

Im running it as a daily driver on my FHD 9360.

**Comment by knowledgegod** [comment]
I have the same model as you do. So far it's been fine I used DVMT preallocation 0x05 instead of 0x04 though to resolve a kernel panic. Mine is a FHD 8th generation i7
