### ISSUE TITLE
Catalina

### ISSUE THREAD

**Issue by knowledgegod** [the-darkvoid/XPS9360-macOS#135]
Has anyone been successful upgrading to Catalina?

**Comment by rostopira** [comment]
@knowledgegod I'm not brave enough to try it on daily-driver machine :D

**Comment by ars0nboi** [comment]
What needs to be done to boot Catalina dp2? I was able to get catalina dp1 booted and working fine, but Im having trouble getting dp2 to boot. Such a roadblock.

**Comment by ElieMyIdea** [comment]
Hi,

is there any news about OSX 10.15 update ?

**Comment by knowledgegod** [comment]
You can pretty much boot into Catalina installer with darkvoid settings

**Comment by the-darkvoid** [comment]
macOS Catalina 10.15 (and 10.15 supplemental update - 19A602) works fine with the current repository.
