### ISSUE TITLE
Catalina dp2

### ISSUE THREAD

**Issue by ars0nboi** [the-darkvoid/XPS9360-macOS#137]
What needs to be done to boot Catalina dp2? I was able to get catalina dp1 booted and working fine, but Im having trouble getting dp2 to boot. The acceleration will not work, nor can i even reach the desktop after verbose without it. 12345678 doesn't work for graphics either.  Such a roadblock.

**Comment by chisacam** [comment]
[myEFI.zip](https://github.com/the-darkvoid/XPS9360-macOS/files/3315819/myEFI.zip)
well, if your xps spec is same(or like) mine, this efi will work fine. :)
i'm on db2 work fine.

i7 8550U
8gb ram
256gb nvme ssd
QHD+ touch

if your ram is 16gb, don't forget edit config.plist...

**Comment by rostopira** [comment]
@chisacam I have same spec, but 16gb/512gb
What exactly I have to edit in config?

**Comment by rostopira** [comment]
@the-darkvoid maybe it's a good idea to create gitter chat for such discussions?

**Comment by buhlaze** [comment]
this worked for me.

**Comment by chisacam** [comment]
@rostopira open config.plist with Clover configurator and edit SMBIOS tab.(maybe you will find RAM info.)

**Comment by the-darkvoid** [comment]
macOS Catalina works with both Clover and OpenCore in the repository.

Started from an installation USB created with installinstallmacos.py from https://github.com/munki/macadmin-scripts.

Formatted existing APFS container and installed a clean copy of macOS Catalina
