### ISSUE TITLE
BIOS 2.10.0 compatibility

### ISSUE THREAD

**Issue by rostopira** [the-darkvoid/XPS9360-macOS#138]
I had issues with my laptop, and brought it to the service center
They have updated my BIOS to 2.10.0 and now it doesn't even launch Clover
If it's first in boot sequence, it just ignores it
If it's the only entry in boot sequence, then it launches assistant for check
Any idea, on how to resolve this?

**Comment by rostopira** [comment]
I've also tried OpenCore from this repo, but it's stuck on Apple logo
I would even like to fix and use it, but I have no idea how to enable verbose mode in it, at least

**Comment by businessman9** [comment]
Mount EFI partition and see if clover still in there.

**Comment by the-Quert** [comment]
Disable Secure Boot, and try again.
And boot with a Linux live USB to check your Clover.

**Comment by rostopira** [comment]
@businessman9 yeah, I did that from Windows, it's here
I've even tried to replace all files there with up to date from master branch

**Comment by rostopira** [comment]
> Disable Secure Boot, and try again.
> And boot with a Linux live USB to check your Clover.

Secure Boot is disabled, checked it in the first place, but thanks for advice

**Comment by rostopira** [comment]
Nevermind, not a BIOS version issue
Clover boots, but I got kernel panic
FML, gonna try to solve it now
