### ISSUE TITLE
After using the latest clover EFI(r5018), Can`t find macOS boot option

### ISSUE THREAD

**Issue by WentaoRen** [the-darkvoid/XPS9360-macOS#139]
After using the latest clover EFI(r5018), Can`t find macOS boot option in clover boot options selection.

but using the  r4928 is fine

**Comment by ElieMyIdea** [comment]
Same for me here, I had to boot on a Linux Live to restore my bootloader

**Comment by the-Quert** [comment]
Check the structure of your Clover. Everything work fine with Clover r5027 on macOS 10.14.6

**Comment by WentaoRen** [comment]
> Check the structure of your Clover. Everything work fine with Clover r5027 on macOS 10.14.6

I just delete my old Clover folder, and copy the complete Clover folder from this repository  to the EFI folder

**Comment by ElieMyIdea** [comment]
> > Check the structure of your Clover. Everything work fine with Clover r5027 on macOS 10.14.6
> 
> I just delete my old Clover folder, and copy the complete Clover folder from this repository to the EFI folder

I did the same, as usual.

**Comment by ElieMyIdea** [comment]
I finally created a new CLOVER USB boot (which is working perfectly) [using this guide](https://www.travelertechie.com/2019/01/make-bootable-usb-thumb-drive-with.html), and replaced the files from the usb key to my EFI partition. It's now working perfectly.

**Comment by the-darkvoid** [comment]
Perhaps with a full copy, there's a config.plist issue. I'll check if there's any glaring differences between my running version and the github sample copy.

Note that you should always customize your config.plist with your own serial information and not just copy the default template one over.

**Comment by WentaoRen** [comment]
it's resolved.just using the usb boot .
