### ISSUE TITLE
UVC2FaceTimeHD.kext

### ISSUE THREAD

**Issue by kob** [the-darkvoid/XPS9360-macOS#140]
Hi, @the-darkvoid  ,The UVC2FaceTimeHD.kext cannot work in catalina, I deleted this file in clover , system find the device named "integrated_webcam_HD",but in connot work，when I reopened the photobooth  get a black screen。

**Comment by kob** [comment]
My camera is Sonix Technology Webcam, device ID [0c45:670c]

**Comment by kob** [comment]
My webcam  issue had been fixed
code：
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDevelopmentRegion</key>
	<string>English</string>
	<key>CFBundleIdentifier</key>
	<string>com.Rama.driver.FaceTimeHD</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>FaceTimeHD</string>
	<key>CFBundlePackageType</key>
	<string>KEXT</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleVersion</key>
	<string>2.4</string>
	<key>IOKitPersonalities</key>
	<dict>
		<key>UVC Device</key>
		<dict>
			<key>CFBundleIdentifier</key>
			<string>com.apple.driver.AppleUSBMergeNub</string>
			<key>IOClass</key>
			<string>AppleUSBMergeNub</string>
			<key>IOProviderClass</key>
			<string>IOUSBDevice</string>
			<key>IOProviderMergeProperties</key>
			<dict>
				<key>USB Product Name</key>
				<string>FaceTime HD Camera (Built-in)</string>
				<key>USB Serial Number</key>
				<string>CC2C960ENHDN9KE0</string>
				<key>USB Vendor Name</key>
				<string>Apple Inc.</string>
				<key>bcdDevice</key>
				<integer>32805</integer>
				<key>iManufacturer</key>
				<integer>1</integer>
				<key>iProduct</key>
				<integer>2</integer>
				<key>iSerialNumber</key>
				<integer>3</integer>
				<key>idProduct</key>
				<integer>34064</integer>
				<key>idVendor</key>
				<integer>1452</integer>
				<key>kSuspendPort</key>
				<true/>
				<key>non-removable</key>
				<string>yes</string>
			</dict>
			<key>idProduct</key>
			<integer>26380</integer>
			<key>idVendor</key>
			<integer>3141</integer>
		</dict>
		<key>UVC Interface 1</key>
		<dict>
			<key>CFBundleIdentifier</key>
			<string>com.apple.driver.AppleUSBMergeNub</string>
			<key>IOClass</key>
			<string>AppleUSBMergeNub</string>
			<key>IOProviderClass</key>
			<string>IOUSBInterface</string>
			<key>IOProviderMergeProperties</key>
			<dict>
				<key>USB Interface Name</key>
				<string>FaceTime HD Camera (Built-in)</string>
				<key>bcdDevice</key>
				<integer>32805</integer>
				<key>idProduct</key>
				<integer>34064</integer>
				<key>idVendor</key>
				<integer>1452</integer>
			</dict>
			<key>bConfigurationValue</key>
			<string>*</string>
			<key>bInterfaceNumber</key>
			<integer>0</integer>
			<key>idProduct</key>
			<integer>26380</integer>
			<key>idVendor</key>
			<integer>3141</integer>
		</dict>
		<key>UVC Interface 2</key>
		<dict>
			<key>CFBundleIdentifier</key>
			<string>com.apple.driver.AppleUSBMergeNub</string>
			<key>IOClass</key>
			<string>AppleUSBMergeNub</string>
			<key>IOProviderClass</key>
			<string>IOUSBInterface</string>
			<key>IOProviderMergeProperties</key>
			<dict>
				<key>bcdDevice</key>
				<integer>32805</integer>
				<key>idProduct</key>
				<integer>34064</integer>
				<key>idVendor</key>
				<integer>1452</integer>
			</dict>
			<key>bConfigurationValue</key>
			<string>*</string>
			<key>bInterfaceNumber</key>
			<integer>1</integer>
			<key>idProduct</key>
			<integer>26380</integer>
			<key>idVendor</key>
			<integer>3141</integer>
		</dict>
	</dict>
	<key>OSBundleRequired</key>
	<string>Root</string>
</dict>
</plist>
`

**Comment by wzxshhz123** [comment]
@kob Hi, I have the same problem as you. Could you tell me how to get DeviceID and how to edit it in FaceTimeHDCam.kext? Do you mean editing info.plist? Thank you very much!

**Comment by the-darkvoid** [comment]
Great. Thanks for letting others know, your webcam is a different device compared to what is on my machine.

**Comment by RicKrauel** [comment]
> My webcam issue had been fixed
> https://github.com/syscl/XPS9350-macOS/files/1075449/FaceTimeHDCam.kext.zip
> edited adding my DeviceID

Can you explain how you added your DeviceID? I opened the info.plist in the kext but there are several places where I can enter my deviceID
