### ISSUE TITLE
OpenCore freeze during boot

### ISSUE THREAD

**Issue by sashoism** [the-darkvoid/XPS9360-macOS#141]
(I have a working clover installation)

I'm unable to boot with the OC configuration - I get to the apple logo + progress bar, which doesn't move. In verbose mode, the log freezes around VoodooI2CPCIController startup (about 1-2 seconds in). Of course, I have tried disabling VoodooI2C & co. only to freeze on a different line, but roughly at the same time after boot.

I've also tried piecing OC 0.5.0 with the latest kexts together on my own, but I end up with the same result.

I'm curious to know if someone has gotten OC to work, or knows how to resolve this specific issue. I'm unable to debug it since it's unclear what's going wrong exactly.

Differences:
macOS 10.14.5, i5-8250U, 1920x1080
PlatformInfo>Generic changed accordingly
UIScale to "AQ=="
no CPUFriend

Let me know if there's any other useful information I could provide.

**Comment by the-darkvoid** [comment]
The latest commit contains a working OpenCore 0.0.5 setup.
Note that it does also contain a custom compiled VoodooI2C which resolves the OpenCore crash race condition in com.apple.iokit.IOHIDFamily

**Comment by sashoism** [comment]
Thank you for the update, but unfortunately the issue persists.

All I've changed with the new configuration is:
1) remove CPUFriend and -DataProvider
2) MLB, serial number, and UUID
3) verbose flag

Here's a sloppy photo of one example of where the freeze happens:
http://0x0.st/zJIR.jpg

I tried clearing NVRAM, but honestly I have no clue how else to approach this :|

**Comment by the-darkvoid** [comment]
Remove VoodooI2C and see if it gets further.

**Comment by sashoism** [comment]
No luck doing that either: http://0x0.st/zJ0f.jpg

**Comment by Shwise** [comment]
I am facing an error message as well when using IOElectrify (but the OS does boot). It seems this does not work with OpenCore (even though it does boot, the kext does not function). Any chance of updating the kext? @the-darkvoid

**Comment by sashoism** [comment]
@Shwise I am fairly certain the method you're referring to is deprecated in favor of the TYPC SSDT patch.

**Comment by Shwise** [comment]
Hmm . . . without IOElectrify I cannot manage to plug in a dock during sleep and have usb 3 peripherals work when the computer is woken up.

**Comment by yonient** [comment]
I got the same issue. My boot just hang at the exact same point as you. Did you figure out how to resolve it?

**Comment by sashoism** [comment]
@yonient Afraid not mate.

**Comment by egore24** [comment]
Hello DV. I tried the OC boot loader as well and had the same issue as stated here.

Do you have an updated OC working folder? I'd love to try it out. Thanks much!

**Comment by the-darkvoid** [comment]
I've now submitted my working (on XPS 9360 i7-8550U) copy of OpenCore 0.5.1.
The only changes I've applied are the serial number, MLB and ROM values.

**Comment by Gitminksqssss** [comment]
I also encountered the same problem, no matter how to debug or freeze the screen. The same goes for the 0.5.3 update

**Comment by the-darkvoid** [comment]
I'll try and update OpenCore again, its obviously working over here so I am unable to replicate the issue you are experiencing.

**Comment by AutinMitra** [comment]
I had this issue just now, and resolved by disabling "enable legacy boot support" in bios (I assume that's CSM - which opencore does not like?)

**Comment by mpross512** [comment]
Fixed it for me! Thank you!

**Comment by AutinMitra** [comment]
That's great! @the-darkvoid maybe adding to the README to disable legacy boot will make this more clear?

Thanks for all the hard work you put into making the repo, working perfectly on my 9360!

**Comment by the-darkvoid** [comment]
@AutinMitra,

I've checked my BIOS and you are referring to `Advanced Boot Options` --> `Enable Legacy Option Boot ROM`?

**Comment by AutinMitra** [comment]
Yup, disabling ``Enable Legacy Option Boot ROM`` fixes the freeze, at least for me and mpross512

**Comment by bloocool** [comment]
Disabling `Legacy Option Boot ROM` fixed the freezes, for me as well.
Thank y'all!

**Comment by the-darkvoid** [comment]
Has anyone updated OpenCore to 0.5.8 yet?

**Comment by bloocool** [comment]
@the-darkvoid I am working on it now. No luck so far I keep getting a kernel panic. I'll keep you all up to date.

**Comment by the-darkvoid** [comment]
Ok, so its not just me. Getting an instant kernel panic as well.

**Comment by bloocool** [comment]
I created a new issue [here](https://github.com/the-darkvoid/XPS9360-macOS/issues/161) for others who may have the same issue in the future.
