### ISSUE TITLE
CPU Frequence constant at 2.2Ghz in Benchmark with Low fan speed

### ISSUE THREAD

**Issue by JessyTang** [the-darkvoid/XPS9360-macOS#142]
Hi darkvoid, thanks for your great contribution to this repo. Your work greatly help us to hackintosh in xps 9360, nevertheless there are some tips can be improvement.

Recently I found that the i7 8550U performance under macOS different from under Windows 10. In Windows, Cinebench R15 can get 700+cb and CPU Frequence consist with 3.2Ghz@25W. However, in the macOS the Cinebench only get 500+cb.

At the beginning of the benchmark, CPU Temperature rapidly up to 100 degree with 3.8Ghz@50W. After 1 second or less, it down frequence to 2.2Ghz@15W. Through all benchmark, the cpu fan seem doesn't work at all.

I search the issues in this repo and found that reference: [Issue 97](https://github.com/the-darkvoid/XPS9360-macOS/issues/97). But I think the difference from windows and macOS means BIOS Controll is not the reason.

Then I went to test the Macs Fan Control. It can not found any fans. Does it due to VirtualSMC which doesn't contain a Fan Sensor? Will it work to replace with FakeSMC and its Sensor Kexts?

Whatever, thanks for your giant contribution for xps 9360 again!

**Comment by the-darkvoid** [comment]
Even with sensor plugins installed, macOS and tools would only be able to report the actual fan speed.
It does not allow the OS to control the fan speed in any way. On an Apple Mac this is done through the EFI firmware entirely, as it should be through the BIOS on the Dell as well.

You can try and change the OS mode in the ACPI patches to allow the machine to behave more like it does on Windows.

**Comment by JessyTang** [comment]
Thanks for your answer，I will try to find the difference and resolution.
