### ISSUE TITLE
Webcam issue

### ISSUE THREAD

**Issue by sliuweimin** [the-darkvoid/XPS9360-macOS#146]
I have a webcam with a device id [0c45:670c], which is exactly same as the repo. It works fine under windows. However, under hackintosh, without UVC2Facetime.kext, it can be recognized under system info.  But it gives a black screen under any app. With that kext, it shows apple device under system info, but it cannot be recognized by any app. Could it be a usb inject issue?

**Comment by 451725563** [comment]
i have same problem

**Comment by ajtang** [comment]
I didnt have this problem when i was in Mojave. But when I updated to Catalina, it appeared. What OS version are you using?

**Comment by eko133** [comment]
> I didnt have this problem when i was in Mojave. But when I updated to Catalina, it appeared. What OS version are you using?

Catalina as well.

**Comment by ajtang** [comment]
[FaceTimeHD.kext.zip](https://github.com/the-darkvoid/XPS9360-macOS/files/3963622/FaceTimeHD.kext.zip)
Use this instead. :) For catalina users on XPS 9360

**Comment by wanghuangjie** [comment]
not worked under big sur .

Integrated_Webcam_HD:

  Product ID:	0x670c
  Vendor ID:	0x0c45  (Sonix Technology Co., Ltd.)
  Version:	56.26
  Manufacturer:	CN09GTFMLOG0076EB21CA01
  Location ID:	0x14500000

![image](https://user-images.githubusercontent.com/3711191/99944970-bdfd8500-2dae-11eb-8a90-a20fbaae6f82.png)
