### ISSUE TITLE
Kext location

### ISSUE THREAD

**Issue by cem2ran** [the-darkvoid/XPS9360-macOS#15]
Hi @the-darkvoid 

Really appreciate you sharing your setup!

Should the /kexts be placed in S/L/E and /kexts/Library-Extensions in L/E or should they go in EFI/CLOVER/kexts?

**Comment by the-darkvoid** [comment]
Whatever is in /kexts is already in the CLOVER/kexts/Other folder.

Kexts in /kexts/Library-Extensions go into /Library/Extensions. Ideally using the entire /CLOVER folder in boot should allow you to startup.
