### ISSUE TITLE
Clover vs OC Hotpatch Differences

### ISSUE THREAD

**Issue by Nihhaar** [the-darkvoid/XPS9360-macOS#152]
Why is there a difference between base64 encoding of _CRS in "change _CRS to XCRS in device TPD1 (TouchPad I2C)" patch of clover config.plist and oc config.plist? Thanks

FDNfQ1JTAA== -> 3_CRS (base64decode)
X0NSUw== -> _CRS (base64decode)

<img width="558" alt="Screenshot 2020-01-06 at 2 01 46 PM" src="https://user-images.githubusercontent.com/20909963/71806062-e3e24400-308d-11ea-9c7f-e2f8406544d8.png">
<img width="549" alt="Screenshot 2020-01-06 at 2 03 52 PM" src="https://user-images.githubusercontent.com/20909963/71806089-ea70bb80-308d-11ea-972a-bfcd79544b60.png">

**Comment by the-darkvoid** [comment]
Clover uses a TgtBridge to limit the patch, while OpenCore uses only a table signature and skip value of 1.
Because of this, the patch had to be adjusted.

**Comment by Nihhaar** [comment]
I understood that one (TgtBridge and table signature) but my question is why is the encoding of "_CRS" is different among the patches, X0NSUw== vs FDNfQ1JTAA==?

No problem but I'm just trying to understand the concept behind it.

**Comment by the-darkvoid** [comment]
As per your decoded content, the OC patch has an extra byte added to minimize the number of matches, because the area it searches through is larger due to missing TgtBridge functionality.

base64 encodes 6 bits per digit and we are displaying it here per 4 bits, which then changes the entire base64 string.

**Comment by Nihhaar** [comment]
That makes sense. Thank you. Will open this issue again if I have any doubt.
