### ISSUE TITLE
Cannot start MacOS after repair

### ISSUE THREAD

**Issue by SakuraTime** [the-darkvoid/XPS9360-macOS#158]
Hello, my computer's power chip has been damaged recently, I replaced it. After that, MacOS can't start, but Windows can. When I use dvmt.efi to view my variables, I get some warnings, can you tell me why there are these warnings? I tried doing some searching but I didn't get the answer.
![dvmt](https://user-images.githubusercontent.com/36107032/77253811-e1a88280-6c97-11ea-88be-53336510c73f.jpg)

Thanks!

**Comment by SakuraTime** [comment]
tried to run `wmic bios get serialnumber` on Windows and get the correct serial number.

**Comment by R1MnTnA** [comment]
@SakuraTime do you know if they by chance also upgraded your bios version and which version you are on? I'm curious if the latest 2.13 works well with the Mac OS or not. Thanks!
