### ISSUE TITLE
BT4LEContinuityFixup Typo

### ISSUE THREAD

**Issue by wyatt-howe** [the-darkvoid/XPS9360-macOS#159]
BT4LEContinuityFixup.kext is mistyped as "BT4LEConti**un**ityFixup.kext" at `OC/config.plist` and in `kexts/`

**Comment by the-darkvoid** [comment]
Well-spotted and it was actually taken from the source project before:
https://sourceforge.net/projects/bt4lecontiunityfixup/support
https://github.com/lvs1974/BT4LEContiunityFixup.

I see the author of the kext has now resolved the typo in their project so this can be fixed on next update.
