### ISSUE TITLE
Sleep/Wake Issue

### ISSUE THREAD

**Issue by amiles5** [the-darkvoid/XPS9360-macOS#16]
Hi,

Thank you so much for the work you have done here.
Had much more success with your files than with bozma88 LTS guide
After trying many time I have now got my 9360 working almost flawlessly.

trackpad
Audio
iMessage
iCloud
Hi Res Screen

My issue is with sleep/wake. On resume the screen does not allow pointer movement or password entry so have to hard reboot.

Laptop is high Sierra 10.13.3 (latest as at 23 March)
Using HFS not apfs. Wifi card replaced and working

BIOS Version 	2.5.1
BIOS Date 	25/01/2018 
Intel HD Graphics 620 1536 MB
I7 Kabylake CPU

Can you point me in the right direction for fixing/diagnosing this issue?

Many Thanks

**Comment by the-darkvoid** [comment]
I've rarely had the issue after waking up. Unsure why this is happening yet, most likely VoodooPS2Controller.

Next time it happens connect an USB keyboard to login and check the system log.

**Comment by amiles5** [comment]
The machine was actually freezing so USB keyboard didn't help.
I replaced my /CLOVER directory in /EFI (after updating serials etc) with your latest.

after removing an errant BrcmNonPatchRAM2.kext from  /Library/Extensions the issue was resolved.
