### ISSUE TITLE
OpenCore no full model identifier written

### ISSUE THREAD

**Issue by C4ptainC4mp** [the-darkvoid/XPS9360-macOS#164]
Using the the OpenCore setup, the model identifier gets not written properly. It should be 
MacBookPro15,2 
but is 
MacBookPro1 
Because of this problem, Boot Camp Assistant crashes on startup, and Brigardier tries to download Bootcamp support files for model MacBookPro1. 

<img width="655" alt="Screenshot 2020-05-24 at 15 08 12" src="https://user-images.githubusercontent.com/47699554/82754931-995d2c00-9dd0-11ea-847c-fddf77037272.png">

**Comment by egore24** [comment]
Simple. 
Change: Kernel > Quirks > CustomSMBIOSGuid > Yes
Change: PlatformInfo > UpdateSMBIOSMode > Custom

**Comment by the-darkvoid** [comment]
Thanks @egore24. I didn't see the model cut-off issue when testing OpenCore, your suggested changes are now commited.
