### ISSUE TITLE
Install/Boot crashes when mouse appears

### ISSUE THREAD

**Issue by x8BitRain** [the-darkvoid/XPS9360-macOS#17]
Tried reinstalling under 10.13.3 seeing as you added some updated kexts to the repo, but I get as far as, the mouse appearing and the system freezes, can't get much from verbose mode either as the verbose screen disappears just before the mouse shows and booting completes. Might this have something to do with the VoodoI2C?

Thanks

**Comment by x8BitRain** [comment]
Narrowed it down to VoodooI2C not working for some reason, tried to disable it without disabling the rest of the new stuff, doesn't seem to work.

As soon as you get control of your mouse after the boot screen is when the OS freezes.

**Comment by x8BitRain** [comment]
Further narrowed down the issue, it looked like it was the new VoodooI2C causing the crash as it happened as soon as the mouse appears but it's definately a graphics issue.

I have an 8th gen i5 with HD 620 graphics and was using this config from RehabMan's repo to get the installer to boot https://github.com/RehabMan/OS-X-Clover-Laptop-Config/blob/master/config_HD615_620_630_640_650.plist

But because the config in this repo and the one above are so different I'm not sure that any of the DSDTs or kexts are being loaded properly when using RehabMan's config. @the-darkvoid Can these configs be merged somehow to work with HD 620 graphics?

**Comment by x8BitRain** [comment]
Ended up installing 10.13 alone, 10.13.3 just doens't want to install anymore.

**Comment by the-darkvoid** [comment]
@x8BitRain : I have the 8th Gen i7 model with UHD620 graphics. So the plist should be attuned to that.
