### ISSUE TITLE
Gets stuck here

### ISSUE THREAD

**Issue by actuallyliam** [the-darkvoid/XPS9360-macOS#173]
![image](https://user-images.githubusercontent.com/67041888/86338276-79edd480-bc95-11ea-8715-ac7c2e04edea.jpeg)

Any idea what I might be doing wrong? I tried it on bios 13 and 9. Both get stuck here.

**Comment by RicKrauel** [comment]
Did you configure the DVMT variables correctly?

**Comment by actuallyliam** [comment]
> Did you configure the DVMT variables correctly?

As far as I know.

I used these:

0x4de 0x00
0x785 0x04 (as I have the i5 8th 1080p)
0x786 0x03

**Comment by RicKrauel** [comment]
> > Did you configure the DVMT variables correctly?
> 
> As far as I know.
> 
> I used these:
> 
> 0x4de 0x00
> 0x785 0x04 (as I have the i5 8th 1080p)
> 0x786 0x03

Just noticed that you are running OC, I use clover so its out of my loop. Just by googling your latest log „log:EXITBS:START“ some results come up stating that „SetupVirtualMap“ has to be set to „Yes“ in your OC boot file.

**Comment by actuallyliam** [comment]
> > > Did you configure the DVMT variables correctly?
> 
> > 
> 
> > As far as I know.
> 
> > 
> 
> > I used these:
> 
> > 
> 
> > 0x4de 0x00
> 
> > 0x785 0x04 (as I have the i5 8th 1080p)
> 
> > 0x786 0x03
> 
> 
> 
> Just noticed that you are running OC, I use clover so its out of my loop. Just by googling your latest log „log:EXITBS:START“ some results come up stating that „SetupVirtualMap“ has to be set to „Yes“ in your OC boot file. 

I’m using clover as far as I know. When I boot it boots into clover. I mostly followed Mark Perez guide for Mojave on his XPS 9360. With the only difference being I used gibMacOS as I don’t have another Mac anymore to create the USB.

And it even contains the option to use open core instead of clover which I didn’t select. So I’m not sure why it’d be trying to use OC.
