### ISSUE TITLE
tb3 dp output failed

### ISSUE THREAD

**Issue by abstract-liu** [the-darkvoid/XPS9360-macOS#182]
Hi friend, 
my laptop is xps13 9360 with 7200u and uhd620 graphic card,  bios version is 2.9.0, catalina 10.15.7
I fully use your EFI. Everything is Okay, except for tb3 dp output. The system can detect it showing in the settings-monitor, but the monitor is black... Besides, the hdmi output is okay.
I would be greatly appreciated if you could help me figure out this problem.
Thx~

**Comment by mankot14** [comment]
TB3 is finicky. You'll need to boot the machine after plugging in the TB3 cable for the DP functionality to work. You cannot hot-plug TB3 devices.

**Comment by abstract-liu** [comment]
> TB3 is finicky. You'll need to boot the machine after plugging in the TB3 cable for the DP functionality to work. You cannot hot-plug TB3 devices.

yeeh, I finally made it work... in a strange method. 
First, I have to plug in hdmi monitor before os start.
Then, after entering os, I can plug in dp input to my tb3 docker,,, and reopen monitor a few times....
I think it may be the problem with display memory allocation?
Last, thank u very much :)
