### ISSUE TITLE
Install steps?

### ISSUE THREAD

**Issue by vinv** [the-darkvoid/XPS9360-macOS#2]
Hi,

I'm trying to use your repository to get HS running on my 9360 (FHD, i7, EVO SSD), but the install won't complete. The steps I followed -

1) Create a HS install disk
2) Install Clover on that disk
3) Replace the CLOVER folder with the one from your repository
4) Boot into the UEFI shell and change 0x785 to 0x2 (given, FHD) and 0x4de to 0x0. 0x786 was already at 0x2 (and given FHD, I didn't think to change to MAX)
5) Start install. It reboots once, then loads up the GUI and starts to install. Towards the end, it throws a "could not complete installation". When I reboot, a new "Boot MacOS" option is available, but again fails to load; the progress bar just hangs until I reboot.

Given the issues, I think there must be something fundamental I'm missing. Please advise - Is the config.plist in the Clover folder correct? Are the above steps correct?

Thanks,
Vin

**Comment by x8BitRain** [comment]
Yeah, I'm not too familiar with the whole UEFI shell and I can't figure out how to change those values with the command you mentioned, some detailed steps would be appreciated, thanks.

**Comment by egore24** [comment]
@vinv When you reboot and "Boot MacOS" option is there, is there still a "Install......" boot option, or is that gone? If it's gone, the install should be complete. Have you then booted with the install USB to get to HS and replace the Clover folder on the SSD EFI?

**Comment by vinv** [comment]
@egore24 There isn't a "Install..." boot option, but note that the install explicitly failed with "Could not complete" (UI still intact). I did reboot thereafter via the install USB to the "Boot HS" option, but it hangs there. 
I'm just concerned I'm doing something fundamentally wrong due to the fol. facts - the ig-platform-id in the config.plist is 0x0, both Intel and Nvidia are false. One of the times I got stuck it hung trying to load gfx firmware (I had verbose boot enabled). When I explicitly specified disablegfxfirmware, that didn't happen, but it hung somewhere else of a 240s timeout, i think.
Can you confirm that the above steps I followed are correct and that the config.plist in the repo is good? I'm using Clover 4334

**Comment by egore24** [comment]
I'm not sure what the issue is. I had the same install fail, but booting the install disk worked just fine. I simply took the referenced Clover folder here and put it in the HD EFI (only changing SMBIOS) and it has worked for me. Not sure the BIOS changes you did are for FHD displays. I did do them, but I have a QHD display.

**Comment by vinv** [comment]
@egore24 Thanks. Is simply copying the CLOVER folder into the SSD's EFI volume enough? We don't need to "install' Clover? If so, the only difference between what you did and I was that (after the install failed), I didn't boot to USB, mount the SSD and copy the CLOVER folder into the SSD, then reboot into the SSD. I'm going to try that. What did you mean by changing SMBIOS?

**Comment by egore24** [comment]
Using Clover Configurator to change the SMBIOS information in the Clover config file.

**Comment by vinv** [comment]
No go. It almost seems like Clover doesn't "see" the config.plist. There are default boot arguments specified that it doesn't apply. There is a SMBIOS entry for MacBookPro14,1 it doesn't see - defaults to something else. Not sure what's going on.

**Comment by the-darkvoid** [comment]
If you press 'o' to enter clover options you can see what data it is using from the config.plist as well as what config.plist it is loading.

Validate that first.

**Comment by vinv** [comment]
@the-darkvoid I have no idea what was going on, but I downgraded to an older Clover (4268) and it started to pick up config data from config.plist. I was able to install successfully, but get a kernel panic on the first reboot thereafter. I've enabled verbose, keep symbols on panic and don't restart, but the panic data scrolls by too fast. It only dumps out a list of kernel extensions at the end. Is there any way to scroll in verbose boot or is the boot log captured anywhere? This is the OSx boot, not the log from Clover.

**Comment by vinv** [comment]
I took a video of the panic and although blurry, I think the failure is from
AppleIntelController.cpp Assertion failed: minStolenSize <= fStolenMemorySize

Am I missing some configuration?

**Comment by the-darkvoid** [comment]
DVMT setting in bios is incorrect. Increase the size.

**Comment by vinv** [comment]
I did end up updating DVMT settings eventually (0x785=0x4 and 0x786=0x3), but I think what fixed it was setting FixIntel to true and an ig-platform-id of 0x519b0000. I think I have everything running correctly now.

**Comment by Acen-Fr** [comment]
Good morning, first of all I'm a noob, I'd like to know if I can follow these steps without problem, I have FHD, i7 8550, sotck SSD (toshiba) and DW1560 wifi card.
Should I modify something other than readme.md ? 
Thank you.
