### ISSUE TITLE
Sleep/Wake Issues - Again

### ISSUE THREAD

**Issue by amiles5** [the-darkvoid/XPS9360-macOS#21]
Hi - Further to my Issue 16 I still have freezing on Wakeup....

If I use the script option "--patch-hda" to Create AppleHDA injector kernel extension then the freezing occurs. If I remove AppleHDA_ALC256.kext from /Library/Extensions sleep/wake is functional again but no sound. Could this be an Issue with Codec Commander?

I have repeated the install many times with 23 March Release - same issue. (both APFS & HFS plus)
Tried using latest CLOVER folder with AppleALC (layout-id 56) from latest release - same issue.
Its a shame since the machine is superb - just no sound with sleep/wake.

Regarding your latest updates commencing around 23 March - the CLOVER folder on USB installer no longer boots on my 9360 ? Verbose mode doesnt help since progress bar pops up and hangs as noted by x8BitRain in issue 17.

Once again thanks for the great repo!!

**Comment by amiles5** [comment]
So - updated to 10.13.4 with combo updater and also added this ...

```
<dict>
                <key>Comment</key>
                <string>USB 10.13.4+ by PMHeart</string>
                <key>Disabled</key>
                <false/>
                <key>Find</key>
                <data>
                g32UDw+DlwQAAA==
                </data>
                <key>InfoPlistPatch</key>
                <false/>
                <key>MatchOS</key>
                <string>10.13.x</string>
                <key>Name</key>
                <string>com.apple.driver.usb.AppleUSBXHCI</string>
                <key>Replace</key>
                <data>
                g32UD5CQkJCQkA==
                </data>
            </dict>
```
Which seems was required on my other Hack to fix USB.

With "AppleHDA_ALC256.kext" generated before the update sleep now  works with Audio enabled.

**Comment by the-darkvoid** [comment]
The last few commits have included AppleALC.kext for dynamic patched sound.
You could try that instead of the --patch-hda option.

**Comment by amiles5** [comment]
Since everythings working I'm a Happy Camper !!! Now an awesome notebook.

**Comment by meiyouren** [comment]
I met the same problems as you. if I remove AppleHDA_ALC256.kext from L/E,the headphones  have strong wave sounds.And the headphones  are always no sound while Wakeup.how do u fix this problems.
