### ISSUE TITLE
App Store access

### ISSUE THREAD

**Issue by cem2ran** [the-darkvoid/XPS9360-macOS#22]
Just wanted to know if you @the-darkvoid are able to download apps from the App Store or if the following is needed? https://github.com/RehabMan/OS-X-Null-Ethernet

**Comment by the-darkvoid** [comment]
Once a compatible WiFi card is installed you do not need OS X Null Ethernet.

**Comment by cem2ran** [comment]
I managed to solve the issue by clearing my network interfaces. I initially setup my machine with an incompatible Wifi Card and didn't have an en0 interface.
