### ISSUE TITLE
Can't get to installer screen

### ISSUE THREAD

**Issue by webprogrammingsolutions** [the-darkvoid/XPS9360-macOS#23]
Same laptop, XPS 9360 with i7 8550 cpu, Intel 620, QHD screen. 2.6.2 Bios, all settings set correctly.

I'm creating an installer with Unibeast and then copying over your clover folder to the EFI mount. 
Am I missing a step?

Loading bar gets half way and stalls. When booting with verbose mode on, I get to the following line and then kernel panic:

considerRebuildOfPrelinkedKernel com.alexandred.VoodooI2CServices triggered rebuild

**Comment by the-darkvoid** [comment]
Unibeast is not a good choice for laptops. Use the installation guide by Rehabman.
Good place to start is here:
https://www.tonymacx86.com/threads/guide-dell-xps-13-9360-on-macos-sierra-10-12-x-lts-long-term-support-guide.213141/
