### ISSUE TITLE
Can't boot anymore :/

### ISSUE THREAD

**Issue by necrodst** [the-darkvoid/XPS9360-macOS#24]
Hello, 

I don't know why I can't boot anymore on my Hackintosh 10.13.4 ... 
Everything was running perfectly until I restarted my computer yesterday.

I've got a loading wheel at the very end of the boot sequence (just before the login screen).
When I go to verbose mode I can see that this message is shown in loop : 
gioscreenlockstate 3 hs 0 bs 0 now 0 sm 0x0 9360

I tried to see what files may have been modified in Single User Mode but without success..

Also, I couldn't boot anymore on the USB install key I used before to install... Such a very strange situation... I verified my BIOS settings, I didn't notice modifications :/

Hope you could bring me some help.

**Comment by the-darkvoid** [comment]
The log entry is the last before the user interface card kicks in. This indicates issue with CoreDisplayFixup or the Intel device ID.

Try connecting an external monitor or alternatively override the Intel device ID in SSDT-Config.aml with 0x12345678.
