### ISSUE TITLE
DW1830 bluetooth support 

### ISSUE THREAD

**Issue by phuanh004** [the-darkvoid/XPS9360-macOS#25]
Hello,

Can you update some kexts to help the bluetooth working on XPS-9360?

Thank you

**Comment by the-darkvoid** [comment]
My DW1830 card is broken, not looking to add support for this card at this time anymore.

I strongly advise a Broadcom BCM94352Z based card, so far its the most compatible across macOS versions, and the antenna connectors match the Dell XPS9360.
