### ISSUE TITLE
9370 Support?

### ISSUE THREAD

**Issue by thedoctor** [the-darkvoid/XPS9360-macOS#27]
`[backstory]`
Just discovered the 9360 has these great resources for hackintoshing out. 
I happen to have recently switched from a macbook to a 9370 and I have been disappointed by how far the linux desktop ecosystem hasn't come since I left.
I wasn't sure where to ask this question, so if there's a place just point me there and close this.
`[/backstory]`

Does anyone know if this guide has been tested on a 9370?

**Comment by cem2ran** [comment]
@thedoctor It'll probably work, but you're unable to replace the wifi card on the 9370 sadly.

**Comment by thedoctor** [comment]
@cem2ran Thanks for the reply; I haven't read the whole tutorial yet -- is replacing the wifi card recommended or required? 
I know a lot of people had wifi issues even on Linux with the 9360 but it's been mostly fine for me on Ubuntu 17.10 on the 9370.

**Comment by cem2ran** [comment]
@thedoctor Required unfortunately. At least when I was planning on buying one a few months ago. Killer wifi is not supported.

**Comment by thedoctor** [comment]
Ah well, there goes my plan. Windows/Arch dual-boot, here we go. Thanks!
