### ISSUE TITLE
Bluetooth not available?

### ISSUE THREAD

**Issue by cem2ran** [the-darkvoid/XPS9360-macOS#29]
Has anyone experienced bluetooth not being available in some situations after sleep/closing lid?

For context I'm running the DW1560

**Comment by ToRvaLDz** [comment]
Same here, only bluetooth since 1 or 2 weeks, I will try to update to the latest commit.

**Comment by ToRvaLDz** [comment]
After updating to the latest commit sometimes also the trackpad is not available after closing lid.

**Comment by the-darkvoid** [comment]
My Bluetooth is always working, but I never close the lid to sleep.
I select sleep from the Apple Menu and wait for the powerlight to turn off, after that I close the laptop lid.

My bluetooth device details are:

`Chipset:	20702A3`
 `Firmware Version: v14 c5882`
 `Vendor ID:	0x0A5C`
  `Product ID:	0x216F`

**Comment by the-darkvoid** [comment]
@cem2ran,

Can you confirm your exact bluetooth device and firmware version?

**Comment by cem2ran** [comment]
@the-darkvoid Yes. Exact same. I have not noticed the issue since I disabled sd-card.

**Comment by TrustedDeveloper** [comment]
For those of you having problems with Bluetooth during boot, specifically:
`busy timeout[0] 60s, "bcm20702a0`, add `dart=0` to your Clover boot arguments.

**Comment by jackno** [comment]
I am facing an issue where Bluetooth detects devices but will not pair even after reboot.

Broadcom kexts in `EFI/EFI/CLOVER/kexts/Other`

```
Chipset:	20702A3
Firmware Version:	v14 c4096
Vendor ID:	0x0A5C
Product ID:	0x216F
```

**Comment by the-darkvoid** [comment]
@cem2ran I started enabling the SD card to test. Sofar no issues, but then again I don't have a specific SD card driver loaded.

**Comment by the-darkvoid** [comment]
No issues experienced with SD card enabled or without any `dart` parameter for Clover boot.
`dart=0` should only be required if you haven't configured the BIOS as per the settings documented in the readme.md.
