### ISSUE TITLE
Wifi card compatible ?

### ISSUE THREAD

**Issue by Acen-Fr** [the-darkvoid/XPS9360-macOS#3]
Good morning, I'd like to know which wifi card I can buy, it would be nice if you tell me the model number. 
BCM94352z -> Out of stock in my country (France)

Thanks

**Comment by Acen-Fr** [comment]
BCM943228HMB -> 15€
BCM94352HMB -> 40€

What is the difference please ?

**Comment by Acen-Fr** [comment]
Ok figured it out, best wifi cards compatible are : 
BCM943602BAED
BCM94352z
I'll have to import from china

**Comment by the-darkvoid** [comment]
Save yourself the headache and order specifically the Dell DW1560 from Chinese eBay sellers.
It will take a while to arrive but its definitely the most compatible option and a high quality shielded card.

Be extremely careful when removing the antenna connectors as they are prone to snapping.
I personally use my nails to pull them straight up away from the board with minimal force.

**Comment by Acen-Fr** [comment]
Ordered it yesterday via aliexpress, hope it'll arrive before 12 of january, i'm going to Mexico for 6 months 🙏 
One last question : Did you unplug the battery before removing the wifi card ? Some does, some not.

**Comment by the-darkvoid** [comment]
Yes, you should remove the battery connector and press the power button for a few seconds to drain all residue power from the system. This is the recommended way.

Also refer to the official Dell XPS 9360 service manual, which explains how to remove the wifi card:
http://topics-cdn.dell.com/pdf/xps-13-9360-laptop_service%20manual2_en-us.pdf

I personally use a hard plastic spudger to get the battery connector off:
https://www.ifixit.com/Store/Tools/Spudger/IF145-002-2
