### ISSUE TITLE
Unknown error: -110 upon installing

### ISSUE THREAD

**Issue by jackno** [the-darkvoid/XPS9360-macOS#33]
I know this error is very general so I will explain how this error is produced:

I am using [bozma88's XPS 9360 LTS guide](https://www.tonymacx86.com/threads/guide-dell-xps-13-9360-on-macos-sierra-10-12-x-lts-long-term-support-guide.213141/) to install Hackintosh on my Dell 9360. After all hardware is configured, the BIOS 2.6.2 is configured, and I set up the installation USB as follows:

1. Installation disk is formatted for MBR.
2. Clover is installed to CLOVER EFI using [this guide](https://www.tonymacx86.com/threads/guide-booting-the-os-x-installer-on-laptops-with-clover.148093/) (for installing Clover UEFI on laptops).
3. This repo is cloned locally. (I have tested it with and without the `--compile-dsdt` and `--patch-hda` flags set) *DVMT.efi is renamed to Shell64U.efi.*
4. The files are then copied and merged with the CLOVER EFI partition.
5. macOS 10.13.4 is copied to the install_osx partition using `createinstallmedia`.
6. XPS is booted to Clover and `setup_var`'s are set according to the README.
7. macOS is installed to a HFS+J formatted partition on the same SSD alongside Windows. APFS is disabled using [this guide](https://www.tonymacx86.com/threads/guide-avoid-apfs-conversion-on-high-sierra-update-or-fresh-install.232855/).
8. After installer finishes and reboots, I select `Install macOS High Sierra` from the clover menu as mentioned in the guide.

At this point, the installer displays that it will take 18 minutes to install and after about 5 seconds, the installed fails with the error: **Unknown error: -110**. I don't know how to debug this or even find help since this is such an uninformative error.

Below are my details specs:
Dell XPS 13 (Clover)
i7-8550U, Kaby Lake
Intel UHD Graphics 620, 3200x1800
SSD 1TB Toshiba (partitioned with 200GB for macOS and 800GB for Win10)

**Comment by the-darkvoid** [comment]
Unknown, your device is identical to mine so it should work.
Ask for help in the forum linked in the readme.md.
