### ISSUE TITLE
Keyboard not working after reboot

### ISSUE THREAD

**Issue by kserxes** [the-darkvoid/XPS9360-macOS#36]
First up great work, that was one of my easiest hackintosh installations.

It is pretty much perfect except for one tiny detail and I am wondering if I am the only one to experience this:

I have the i7 version with UHD touch and almost after each reboot the keyboard is not working at the login screen. I say almost because on rare occasions it does work but I have no idea why.
But I have a workaround which is to put the machine to sleep and after I wake it up again the keyboard does work.

Anyone else having this? Ideas on a resolution?

Thanks,
Juergen

**Comment by Zretep** [comment]
I am also having the same issue and @kserxes work around does seem to work. With every reboot the keyboard does not function unless I put it to sleep and wake it back up. Hope someone has a solution to this issue.

**Comment by wmrussell** [comment]
Same issue. Qhd screen and the only way I can get the keyboard to work is to put the computer to sleep. Oddly enough my brightness and audio keys work though?

**Comment by wmrussell** [comment]
Totally Random, But as the system is booting if i keep moving my finger along the touch screen My keyboard will work every time at login.

**Comment by cem2ran** [comment]
Same issue here. UHD as well.

**Comment by agrabsi** [comment]
yep same here and can't install it because I can't type my wifi password ^^

**Comment by Zretep** [comment]
@agrabsi you can plug in a usb keyboard to get past the installation screen.

**Comment by agrabsi** [comment]
@Zretep thanks

For some reason plugging an external keyboard fixed the bug and my xps 13 keyboard works (temporarily ?)

**Comment by wmrussell** [comment]
As pointed out by user "MarkMark2" on tonymac, it looks like booting verbose fixes this as well...Odd.

**Comment by amiles5** [comment]
I updated to the latest CLOVER folder on 15/6 and now I have that issue. Downgraded VoodooPS2Controller.kext back to version 1.8.29 and the issue went away??

**Comment by the-darkvoid** [comment]
No issues experienced with newest VoodooPS2Controller (2018-0506), closing this issue.
