### ISSUE TITLE
Not booting after patching audio

### ISSUE THREAD

**Issue by genesixx** [the-darkvoid/XPS9360-macOS#4]
Hello, 

I recently try to use HS on my xps9360. i'm using all your work (thanks for it btw). When I try patch hda it doesn't boot anymore (verbose says nothing cause it goes to Apple logo).

How can I fix that 

Regards

**Comment by the-darkvoid** [comment]
HDA just places a kext into /S/L/E, it should not prohibit booting.
Try booting in verbose mode for more information.

**Comment by genesixx** [comment]
as i said it's stuck after the verbose and at the apple logo

**Comment by Omaha2002** [comment]
Same for me, tried installing twice, patch audio with the --patch-hda option. HDA and codeccommander are being copied and installed in S/L. XPS doesnt boot anymore afterwards. Booting in safemode and removing HDA and Codeccommander makes the XPS boot again.

**Comment by the-darkvoid** [comment]
@Omaha2002 , @genesixx : Others are successful in running the installation (as per issue #8), unsure what you are doing different.

**Comment by genesixx** [comment]
Idk i'm running voodoo patcher right now and sound work but the amp isn't deactivated and i have a coil whine

**Comment by the-darkvoid** [comment]
IMHO AppleHDA is the preferred implementation with the best native results, you can however use AppleALC as an alternative to the kext approach. It patches the codec dynamically, but the results were not as feature complete which is why I switched to an injector kext.

**Comment by genesixx** [comment]
I still don't get why it's not booting after patching the audio it's weird and i have no idea how to get logs

**Comment by the-darkvoid** [comment]
Potentially a problem rebuilding the kext cache?

The installation installs CodecCommander and an injector kext into /L/E. None of these kexts are known to cause problems.

Verbose boot would be the only way to see more, but as you mentioned there is no more visible information.

Are you use you are rebuilding the cache with KextUtility?

**Comment by genesixx** [comment]
yep i use kext utility, Well going to retry right now and see

**Comment by genesixx** [comment]
so yep installed from scratch clone the repo then 
` sudo sh xps9360.sh --patch-hda` 
then i ran kextUtility then reboot and stuck at apple logo with half the bar done

**Comment by genesixx** [comment]
here a log when I run in safe mode https://gist.github.com/anonymous/99b6dc9b9d23bc0beb7998adad1405d4 dunno if it can help

**Comment by ToRvaLDz** [comment]
Same here, stuck at apple logo after installing hda patch.

**Comment by asinggih** [comment]
Yeah, im also stuck at the apple logo with the half bar done after running `xps9360.sh --patch-hda`., and rebuilding kext cache. Issue persists after reinstalling OSX. Can't even boot to OSX on safe mode.

**Comment by the-darkvoid** [comment]
Rolled back to AppleALC now that it has resolved issues with headphone insertion on XPS 9360.
Commit #6d7c511 should resolve this issue.
