### ISSUE TITLE
Latest VoodooI2C update causing erratic scrolling

### ISSUE THREAD

**Issue by mstansberry** [the-darkvoid/XPS9360-macOS#41]
Tried the latest updates pushed this afternoon on 9360 i7-8550u and noticed that 2-finger scrolling speed was MUCH faster and less responsive to small swipes. Switched back to previous `VoodooI2C.kext` and behavior returned to normal so I believe the issue would be upstream/with the rewrites in `clover.plist`.

Would dig into this more deeply but unfortunately I'm still learning a lot of this. Please let me know if there is any additional info I can gather to assist.

**Comment by the-darkvoid** [comment]
VoodooI2C seems iffy at least. The author is working on a native touch branch, lets wait for that to mature.
In the meantime the repo is reverted to use VoodooPS2Controller
