### ISSUE TITLE
BrcmPatchRAM2.kext + BrcmFirmwareRepo.kext needed?

### ISSUE THREAD

**Issue by koseduhemak** [the-darkvoid/XPS9360-macOS#42]
Why should BrcmPatchRAM2.kext + BrcmFirmwareRepo.kext installed? My Wifi is working even without that two kexts in /Library/Extensions.

Thank you for clarifying :)

**Comment by mstansberry** [comment]
Those kexts make bluetooth work

**Comment by koseduhemak** [comment]
Thank you.
