### ISSUE TITLE
No audio when resuming from sleep

### ISSUE THREAD

**Issue by 28spawn** [the-darkvoid/XPS9360-macOS#43]
HDA patched, no audio when resuming from sleep, if I had the headphone attached I have to remove, if I did not have anything I have to plug a headphone and remove to make the speakers to work again.

**Comment by the-darkvoid** [comment]
Is CodecCommander.kext installed in /System/Library/Extensions?

**Comment by 28spawn** [comment]
no its under /Library/Extensions with AppleHDA_ALC256.kext, should I try to move?

by the way 2.7.1 bios works just fine no need for changes, you should try

**Comment by mstansberry** [comment]
> by the way 2.7.1 bios works just fine no need for changes, you should try

tested this and power management seemed VERY poor. Am guessing a number of the patches would need to be updated for it to work properly on latest BIOS

**Comment by 28spawn** [comment]
really? here is idling just fine, but I use with power supply all the time, but anyway, changed the CodecCommander and AppleHDA_ALC256.kext to /System/Library/Extensions and problem persist, there is any way I can check what is happening on the background

**Comment by 28spawn** [comment]
fixed by changing the Sleep Nodes from SSDT-ALC256.dsl from "n" to "y" and recompiling

**Comment by the-darkvoid** [comment]
@28spawn,

Thanks, though I haven't experienced this issue, I made a prudent update based on your findings in commit f2283c4.
