### ISSUE TITLE
LPC / fan control, sensors

### ISSUE THREAD

**Issue by sbaier1** [the-darkvoid/XPS9360-macOS#44]
I have been struggling to figure out how to get LPC to load and work properly. this would be a nice feature, as it would also allow for fan control from the X86Platform driver as far as i know. however, it seems that on dell laptops the LPC device is structured differently in the ACPI tables(?)

no patches or guides i have tried yielded any results, and even on windows, fan sensors behave oddly.

have you attempted to figure out how t o get this to work? it would be great to have in conjunction with HWP because it may also mean less thermal throttling on heavy workloads, as the fan control could anticipate load and adjust the fan accordingly.

**Comment by the-darkvoid** [comment]
@sbaier1,

Commit 756e782 adds SSDT-LPC.dsl which makes AppleLPC.kext load successfully.

    sudo kextstat | grep LPC
    71    0 0xffffff7f8351b000 0xd000     0xd000     org.hwsensors.driver.LPCSensors (1758) 8FDA3C1B-8BC0-3ABA-BD6D-D24209C20369 <38 12 11 7 5 4 3>
    148   0 0xffffff7f8353a000 0x3000     0x3000     com.apple.driver.AppleLPC (3.1) 7C24E741-BD4A-3917-83AC-E956A03ADC20 <103 12 5 4 3>

Do let me know if you see any positive results testing with this combination.
Pending your feedback, I will can either remove SSDT-LPC or keep it.

**Comment by sbaier1** [comment]
thanks, but it seems as per https://www.tonymacx86.com/threads/lpc-acpi-sensors.115707/
we would probably need to patch PtidDevc table to get LPCSensors to find the values...

not sure if this is worth the effort though... did not see any noticable power consumption difference with AppleLPC loaded so far

![screen shot 2018-07-08 at 14 14 35](https://user-images.githubusercontent.com/20339314/42419631-4ea70de0-82b9-11e8-887a-fedae3565b56.png)

**Comment by sbaier1** [comment]
not sure if anyone has considered this yet, but here's the power gadget log for a load test:

![screen shot 2018-07-12 at 18 08 23](https://user-images.githubusercontent.com/20339314/42645666-ea0c2386-85fe-11e8-9030-699f3880284e.png)

again, i don't know if it's worth the effort but this clearly shows that there is much to be optimized.
On windows, the fan immediately spins up to high gear when a large cpu work load kicks in.

but this default policy we are running on only spins up the fan after a notable delay and doesn't turn it onto a higher duty cycle even when a load persists for longer amounts of time, leading to significant thermal throttling.

**Comment by the-darkvoid** [comment]
@sbaier1 Temperature sensors through ACPI EC queries for FakeSMC have now been implemented in commit 53f2aa8.

I am working on fan speed status as well as fan control, though I think the BIOS does a good job at managing the fan speeds.

**Comment by the-darkvoid** [comment]
@sbaier1, 

With your request in mind, I developed a new driver FakeSMC_SMMSensors.kext,
this allows using Dell System Management Mode to get tachometer (fan) information from the system.

Ideally it could also be used to set/control fan speeds through HWMonitor, but I am not sure if its worth the effort implementing. It would be possible to damage your hardware if wrongly used.

You can see the changes in commit a9b51e2

**Comment by the-darkvoid** [comment]
@sbaier1,

Closing this because the requested functionality is provided.
