### ISSUE TITLE
Sometimes iris plus 640 wakes up to black screen

### ISSUE THREAD

**Issue by hoanX** [the-darkvoid/XPS9360-macOS#47]
hi darkvoid：

First of all, thank you very much for your tutorial.

i7-7560U （intel Iris Plus Graphics 640）, ig-platform-id : 0x59260002
QHD+ Screen (3200x1800)
macOS 10.13.6
PM961 NVMe SAMSUNG 512GB

There is a certain chance that a black screen will appear after sleep wakes up.
I found a similar problem with [syscl (xps9350,Iris Plus 540)](https://github.com/syscl/XPS9350-macOS).
This is his patch

```
Name:AppleIntelSKLGraphicsFramebuffer
find:	0A0B0300 00070600 03000000 04000000
replace:0F0B0300 00070600 03000000 04000000
comment:Enable lid wake for 0x19260004 credit syscl/lighting/Yating Zhou 
```

I also made my own reference to his patch.

```
Name:AppleIntelKBLGraphicsFramebuffer
find: 0A0BE300 00070600 03000000 04000000
replace:0F0BE300 00070600 03000000 04000000
comment:Enable lid wake for 0x59260002
```

After adding the patch, sleep wakes up everything is normal，After adding the patch, sleep wakes up everything is normal, but there is a probability of appearing  Screen flicker.Such as the screenshot below

**Comment by the-darkvoid** [comment]
Please note that for my device I am using `ig-platform-id` of `0x59160000` with my i7-8550U (Intel Graphics 620 UHD), did you try using that? Because I've never had this issue.

(Thought I see the default in SSDT-IGPU.dsl is 0x59260002 for your device ID)

**Comment by hoanX** [comment]
thank you for your reply，cannot start using 0x59160000
PM961 is working fine, no patches used

**Comment by the-darkvoid** [comment]
PM961 with APFS? Or formatted as HFS.

Not sure about your ig-platform-id issue as I don't have this issue to replicate and debug.

**Comment by hoanX** [comment]
APFS working fine

**Comment by the-darkvoid** [comment]
Unable to replicate this issue on my newer Kabylake processor.

Should you come with a fix, I can merge it for others if it looks solid.

**Comment by hoanX** [comment]
hi darkvoid：
