### ISSUE TITLE
No more sound on 10.13.6

### ISSUE THREAD

**Issue by ElieMyIdea** [the-darkvoid/XPS9360-macOS#48]
Hi, I updated to 10.13.6 and repatched AppleHDA with your script. 
I have no sound anymore ! Maybe I miss something

Thanks for your precious work and your help :)

**Comment by the-darkvoid** [comment]
Ensure you don't have AppleALC loaded in kextstat.

**Comment by ElieMyIdea** [comment]
`kextstat | grep AppleALC` return nothing.

**Comment by ElieMyIdea** [comment]
And, like reported by cerberettin on [TonyMacX86 forum](https://www.tonymacx86.com/threads/guide-dell-xps-13-9360-on-macos-sierra-10-12-x-lts-long-term-support-guide.213141/page-244#post-1776270), brightness keys stopped working as well.

**Comment by ElieMyIdea** [comment]
My trackpad clic and multitouch (expect right-clic with 2 fingers) also stopped working but this is probably due to the beer that I accidentally spilled on my computer last week. Hopefully everything is working perfectly except for the trackpad.. I plan to replace him

**Comment by the-darkvoid** [comment]
Try rebuilding your kext cache using [kext utility](http://cvad-mac.narod.ru/index/0-4) or similar first.

**Comment by ElieMyIdea** [comment]
That's perfect !! Thanks a lot, that fixed the issue. Everything's back to normal.

**Comment by dderrida** [comment]
hi
audio still does not work for me , even after a kext rebuild
kextstat | grep AppleALC
   36    0 0xffffff7f83494000 0xce000    0xce000    as.vit9696.AppleALC (1.2.8) 0E6F869C-BE82-34E8-AF07-85187DF84B1D <35 12 7 5 4 3 2 1>

**Comment by TrustedDeveloper** [comment]
Echoing @dderrida on here:
```
kextstat | grep AppleALC
   36    0 0xffffff7f833bf000 0xce000    0xce000    as.vit9696.AppleALC (1.2.8) 0E6F869C-BE82-34E8-AF07-85187DF84B1D <35 12 7 5 4 3 2 1>

```
No audio here either.

**Comment by the-darkvoid** [comment]
If AppleALC is loaded, remove AppleALC from Clover kexts.
Instead run XPS9360.sh --patch-hda to create an AppleHDA injector.
