### ISSUE TITLE
TB3 NVM 26 upgrade

### ISSUE THREAD

**Issue by wilvancleve** [the-darkvoid/XPS9360-macOS#49]
Just wondering what mechanism folks are using to upgrade the firmware? I've been able to update the BIOS using a USB stick, but from the little bit I can glean from google-fu, that's not going to get it done for the TB3 NVM...

Thanks!

**Comment by the-darkvoid** [comment]
Assuming you are running macOS as your primary OS on your internal drive, you'd need to do the following:

- Prepare an USB with [Windows To Go](https://www.microsoft.com/en-us/download/details.aspx?id=48127)
  (Easiest tool is [Rufus](https://rufus.akeo.ie/))
- Install [Thunderbolt drivers from Dell](https://www.dell.com/support/home/us/en/04/product-support/product/xps-13-9360-laptop/drivers)
- Turn all Thunderbolt options (pre-boot adapter) on in the BIOS
- Connect a Thunderbolt device before boot (to ensure Thunderbolt controller is switched on)
- Flash [Thunderbolt firmware from Dell](https://www.dell.com/support/home/us/en/04/product-support/product/xps-13-9360-laptop/drivers)

Note that after upgrading to Thunderbolt NVM 26, I have noticed that USB-C connectivity has been more stable with regards to both USB-C dock & display plugging/unplugging.
