### ISSUE TITLE
OS Freezes every 2-10 minutes.

### ISSUE THREAD

**Issue by x8BitRain** [the-darkvoid/XPS9360-macOS#5]
I got the OS to install and boot perfectly fine but the OS seems to freeze at random doing seemingly normal stuff. It freezes every 2 or 10 minutes, after the 3rd reboot or so the OS stops freezing and is perfectly usable.

One instance of freezing was when I was looking through the log menu to see if I could find anything pointing to a specific error or kernel panic, froze when opening certain logs.

Are there any logs I can look for to pinpoint the specifics of crashes or anything I can do to help prevent the freezes please let me know. Thanks.

**Comment by the-darkvoid** [comment]
@x8BitRain : If the OS is working on every reboot, I doubt it is anything to do with the drivers / kexts used from this repository. I haven't heard a report like this anywhere else.

Try a clean installation from scratch with macOS Sierra 10.13.2

**Comment by timmycarr** [comment]
Just had the same issue with a clean install. Will try a fresh install tomorrow and report back.

**Comment by x8BitRain** [comment]
Did reinstallation fix it? I've narrowed it down to interaction with the MacOS UI, usually context menus are what's causing the freezes but sometimes it's just entirely random.

**Comment by Mnkai** [comment]
I also had this problem, and using HFS+ instead of APFS seems to have fixed this problem.

**Comment by the-darkvoid** [comment]
@x8BitRain, assuming issue closed

**Comment by x8BitRain** [comment]
I never fixed the issue, but was able to make the OS slightly more stable with newer Kexts. 

The OS likes to freeze on certain media related tasks, not video editing in Premier or Photoshop, Sketch, Lightroom, etc, but I've had freezes without fail watching YouTube videos on all browsers, and listening to music through the preview app. 

I am on the 8th gen i5 9360 so that might be an issue?

**Comment by x8BitRain** [comment]
Fixed the issue with a modified config 
[xps9360-8thgen-config.plist.zip](https://github.com/the-darkvoid/XPS9360-macOS/files/1863169/xps9360-8thgen-config.plist.zip)

**Comment by dkkyeremateng** [comment]
@x8BitRain do you now have a stable setup for your specs?

**Comment by x8BitRain** [comment]
No, I gave up in the end, every update took ages to get stable again, for me at least.

**Comment by businessman9** [comment]
What ssd in your 9360?
