### ISSUE TITLE
Issue with USB-C to HDMI adapter and trackpad

### ISSUE THREAD

**Issue by 28spawn** [the-darkvoid/XPS9360-macOS#50]
Hi Darkvoid!

It seems something is not good in your DSDT patching, I just updated to your latest version and now HDMI via USB-C is not working, screen keeps flashing, its recognised but not usable at all, tried charging platform-id and fake-id but no luck, I'm using the 9360 with i7-8550u and connecting to a LG Ultrawide Screen (2560x1080) and the laptop uses the full hd screen.

Beside this there are problems with I2C trackpad, in order to make it work I have to disable the hot patches in config.plist

Any idea about how do address the HDMI issue?

**Comment by 28spawn** [comment]
Problem solved by removing Fakepciid.kext but audio is not recognized for external display

**Comment by 28spawn** [comment]
Got a 9360 with qhd panel and fakepciid works fine with sound, something is different between full hd and qhd

**Comment by the-darkvoid** [comment]
- Disabling the I2C hotpatches reverts you to the PS2 trackpad driver.
- I use two different 2560x1080 QHD monitors with the i7-8550 QHD model without any issues

You'll have to debug this yourself.

**Comment by 28spawn** [comment]
but about the i2c isn't that strange, since right now I'm using exactly the same hardware as you
