### ISSUE TITLE
Coil whine problem

### ISSUE THREAD

**Issue by dderrida** [the-darkvoid/XPS9360-macOS#51]
Hi
Thanks to the hard work of this community I have almost a 100% working 9360 High sierra config (audio, backlight, USB-c, sleep...). The only annoying problem is this unpleasant noise particularly when connectected to USB-C dock with hdmi out. Any solution / workaround ?
Thanks

**Comment by the-darkvoid** [comment]
Inherent to the laptop, OS independent. 

Did you do any additional fixes on top on what is present in this repository?
