### ISSUE TITLE
Enable dragging with drag lock

### ISSUE THREAD

**Issue by egore24** [the-darkvoid/XPS9360-macOS#52]
Thanks for all of your work on this!!

With the latest commit and usage of I2C/Voodoo for the trackpad, enabling dragging with drag lock in Accessability is selectable, but the behavior does not work. Any way to enable this? Thanks again.

**Comment by the-darkvoid** [comment]
What does this behaviour do? Or rather what are you looking for?

**Comment by egore24** [comment]
VoodooPS2 recognizes this functionality, but with the latest commit, it has become non-functional. It's located at SysPrefs/Accessibility/Mouse & Trackpad/Trackpad Options/enable dragging box checked/with drag lock selected in dropdown menu. 

This allows a quick double tap with hold on second tap to select an item, allowing a drag and lift and drag until tapped in place to release. Same usage anywhere in the OS for similar needs.

Otherwise, the only way I see to do these tasks is to perform an actual click and hold while dragging (louder and less finger friendly), unless I'm missing some other option with the new commit. Thanks!

**Comment by the-darkvoid** [comment]
I assume you are referring to the latest commit in this repository (not my VoodooPS2 or VoodooI2C clones)?

Has drag lock ever worked with VoodooI2C?

**Comment by egore24** [comment]
Yes, your latest commit. 

Never worked with VoodooI2C. That’s why I’ve avoided it, hoping your hybrid approach would still allows its functionality. Thanks again.

**Comment by egore24** [comment]
Not sure how VoodooPS2 allowed this functionality, maybe it can be enabled in your take of VoodooPS2?

**Comment by the-darkvoid** [comment]
I have an Apple Magic Trackpad to test with. Let me see how the functionality is supposed to work using that and then see what can be done for VoodooI2C.

Though keep in mind, I'm not an expert in the touchpad position and sensitivity calculations, that would be @alexandred.

**Comment by egore24** [comment]
This issue is now resolved with the new version release of VoodooI2C yesterday. This feature is now active and working well. Might want to include the new VI2C version in your next release. Thanks!
