### ISSUE TITLE
Airdrop outbound not functioning properly

### ISSUE THREAD

**Issue by jackno** [the-darkvoid/XPS9360-macOS#53]
Airdrop inbound (receiving files) is functioning correctly, however outbound (sending files) on macOS does not detect other Airdrop devices.

Running on latest commit 1219637d15b624797835369fef5128385c373bec

**Comment by the-darkvoid** [comment]
@jackno:

That does not sound like a driver issue, but rather configuration. There is no reason for one direction to work and not the other based on driver issues.
