### ISSUE TITLE
No sound 10.13.6

### ISSUE THREAD

**Issue by mrhhcc** [the-darkvoid/XPS9360-macOS#54]
Please tell me how --patch-hda uses 10.13.6
Sorry to disturb you

**Comment by ver2go** [comment]
https://github.com/the-darkvoid/XPS9360-macOS/blob/master/XPS9360.sh
so 
`./XPS9360.sh --patch-hda` if you're in the directory with the shell script

**Comment by the-darkvoid** [comment]
Thanks @ver2go.

Though, don't forget `sudo`:

`sudo ./XPS9360.sh --patch-hda`
