### ISSUE TITLE
Could CPUFriend.kexts used with other CPU models like 7200U?

### ISSUE THREAD

**Issue by koseduhemak** [the-darkvoid/XPS9360-macOS#55]
Hi there,

just wanted to know if I can use the CPUFriend.kexts if my CPU model 7200U does not match your (8550). Or do I need to create the CPUFriend.kexts by myself with the correct frequencies for my cpu model as described in https://github.com/PMheart/CPUFriend/blob/master/Instructions.md.

Thanks!

**Comment by the-darkvoid** [comment]
@koseduhemak,

Yes, you should make your own profile making the 7200U in your machine.
Follow the instructions as mentioned in the URL you linked to do so.

I'll see about updating the README.md to reflect this and not including the pre-built CPUFriend.kext by default in the repo.

**Comment by dderrida** [comment]
Did you manage to create the cpu profile for 7200U? Would be great if you could share
Thanks

**Comment by koseduhemak** [comment]
Not yet... If I have some time to concentrate on the notebook again, I will generate one and upload it here.

**Comment by Lobour** [comment]
I would be interested as well :) (I am not sure to understand the instructions to generate the kext files myself...)

**Comment by koseduhemak** [comment]
Well I have the same problems as you guys. I tried to generate one, but since the README of CPUFriend states one should take a .plist file which uses the same processor, I am stuck here (as there is no plist / MacBook with a 7200U processor).
There seems to be a way to generate custom frequency vectors however and generate such a .plist file, but I had no time to do that / look further into this (I think one have to use https://github.com/Piker-Alpha/freqVectorsEdit.sh). As soon as the .plist is modified by Piker's script one should be able to use that plist with CPUFriend... If I am correct, the script uses the corresponding .plist to your board-id you specified in Clover... So far the theory part 😄
