### ISSUE TITLE
2 finger tap on VoodooI2C

### ISSUE THREAD

**Issue by Jern97** [the-darkvoid/XPS9360-macOS#57]
First of all I have to say that VoodooI2C works much better than the VoodooPS2Controller that was used previously. It really is night and day. Most gestures work flawlessly. Only 2 finger tap (to right click) is not consistent. Is this problem unique to my machine or are you experiencing the same behaviour?

PS: Is there any way we can edit the kexts to customise which shortcuts the gestures trigger?

Thanks!

**Comment by egore24** [comment]
Noticing same inconsistent behavior with two finger taps.

**Comment by businessman9** [comment]
Same problem here, with the updated voodooPS2controller.kext still nothing changed.

**Comment by egore24** [comment]
Updated to the newest VoodooI2C released yesterday and this issue is now resolved and working properly.

**Comment by soto2080** [comment]
> Updated to the newest VoodooI2C released yesterday and this issue is now resolved and working properly.

Do you use official release?
I replaced the old one with new release and got Kernel Panic.

**Comment by egore24** [comment]
Yes, using the official release.

**Comment by Jern97** [comment]
You are right, 2 finger tap works reliably now. I didn't get any kernel panics. Awesome!

**Comment by egore24** [comment]
Agreed, I mentioned just that to DV yesterday.

**Comment by Jern97** [comment]
3 finger swipes up and down don't work anymore for me since the update, are you experiencing similar behaviour?

**Comment by egore24** [comment]
Three finger swipes do work for me. It’s the three finger tap for smart zoom that would be nice. 

In what environment are you testing the pinch to zooms? I can then try the same.

**Comment by Jern97** [comment]
The swipes up and down just don't do anything for some reason. I tested pinch to zoom in Chrome and in the gallery. Even horizontal scrolling works with 2 fingers. Normal 2 finger scrolling has also changed. The position of your 2 fingers matters less (which is a good thing) but it is a little less reliable than before.

**Comment by Jern97** [comment]
To be clear, I downloaded v2.1 from here: [https://github.com/alexandred/VoodooI2C/releases](url) and I replaced voodooI2C and voodooI2CHID kexts with the new versions.

**Comment by Jern97** [comment]
It seems that the trackpad does not produce key combinations anymore. It looks like all of the native gesture (those in preferences/trackpad) are working perfectly.  Awesome!
