### ISSUE TITLE
Touchscreen does not work?

### ISSUE THREAD

**Issue by kaedea** [the-darkvoid/XPS9360-macOS#58]
As mentioned in README, does the Touchscreen not work fine? 
I found out Touchscreen worked well in 9550/9560 before and there are videos on youtube showing this.

**Comment by the-darkvoid** [comment]
It actually does work. But then again it makes no sense using it on macOS.
I will update the README accordingly.

**Comment by kaedea** [comment]
Thanks, I just could not get the meaning of 'out of the box'.
