### ISSUE TITLE
No headphone support

### ISSUE THREAD

**Issue by syncmaster851** [the-darkvoid/XPS9360-macOS#6]
Everything works great in my new installed High Sierra 10.13.2, except no Headphone support, any additional steps to enable it ? 

**My Hardware:**
XPS 9360, I7-7500U, 16G Memeory, 512G SSD, Replaced wifi card with BCM94352z, QHD+.  BIOS 2.3.1
CFG Lock / DVMT Pre-allocation / DVMT Total Gfx Memory updated, I didn't load "--compile-dsdt" by myself ( Shall I ?). 
**Steps to enable audio**
$sudo XPS9360.sh --patch-hda
After reboot, it works fine, just no headphone detected even I plugged in and out.

**Comment by Cody6437477** [comment]
Hi, I’m also experiencing this problem on my i7-8550U 9360 with all other configurations and setup same as syncmaster851.

**Comment by syncmaster851** [comment]
Sorry for the confusion I made, after I plug the headphone jack deep enough, the sound from headphone is work fine, the XPS 9360 model is little bit tight.
Thanks for the great work.

@Cody6437477 , you should try it again.

**Comment by Zerui18** [comment]
@syncmaster851 thanks for the tip, that solved it for me as well! (had thought that plugging the headphones too deep would damage the port)

**Comment by the-darkvoid** [comment]
@syncmaster851 , @Zerui18: Thanks for that finding. I'll keep it in mind in case anyone else reports the same issue.
