### ISSUE TITLE
Menu bar battery status

### ISSUE THREAD

**Issue by egore24** [the-darkvoid/XPS9360-macOS#60]
With latest commit, the menu bar battery status percentage no longer updates. Percentage does not change with use until a manual cycle of unchecking "show percentage" and rechecking. Or, if terminal is started, the percentage appropriately updates. 

Also, the graphical representation of plugging in the charger does not update with the lightning bolt in the battery menu bar icon, nor does it disappear (if it's triggered as above to be shown) when the charger is unplugged. Thanks!

**Comment by egore24** [comment]
Wondering if the might be a BIOS level issue? With a shut down, holding ctrl/esc and plugging in the charger, letting the orange/white lights cycle then boot, the battery menu bar works as it should. Something though, will revert it back to the original issue. 

Maybe that helps narrow this down.

**Comment by the-darkvoid** [comment]
I'm planning to look into ACPIBattery and the issues reported when using on APFS.

Now that I'm finished with the sensors implementation this is an interesting one to tackle.

**Comment by egore24** [comment]
Amazing work you've done on everything! I'm sure you'll be able to figure this one out. Thanks!

**Comment by egore24** [comment]
[SSDT-BATT.aml.zip](https://github.com/the-darkvoid/XPS9360-macOS/files/2255159/SSDT-BATT.aml.zip)

MAY have just solved this. Increased FirstPollDelay to 10000 and so far, so good. Attached is the revised SSDT-BATT.

**Comment by overmiao** [comment]
@egore24, Thank you, it works fine on my machine.
BTW, how long can you use your computer after it is full charged?

**Comment by the-darkvoid** [comment]
@egore24, the latest commit has an updated ACPIBatteryManager.kext with a large number of changes. Give it a try to see if it resolves the menu bar percentage reporting issues.

**Comment by egore24** [comment]
@the-darkvoid, will do. Should I remove/disable the SSDT-BATT first, or is that still needed?

**Comment by the-darkvoid** [comment]
I'm using the SSDT-BATT as it is in this repository. I'd test with and without your changes to see if it affects.

The code change is actually quite close to the change you did. Besides cleanup and removing battery tracker dependency, it now waits until the GUI is loaded.

Though since it waits for a load event, if it works correctly, it should be more stable compared to a random delay in SSDT-BATT.

**Comment by egore24** [comment]
I removed the SSDT-BAT and it from sorted order, and all is well. Menubar battery status percentage is being tracked and graphical (lighting bolt) changes with plug/unplug of charger are working now.

**Comment by the-darkvoid** [comment]
The SSDT-BATT in the repository is not meant to influence the battery timings (it contains the default values). However I've updated it now to only override disabling the extended battery functions which are not supported on the Dell XPS 9360 BIOS.

**Comment by egore24** [comment]
Understood. SSDT-BATT (current revision) is back and also added to sorted order. All is well with the menubar battery status. Great work.
