### ISSUE TITLE
Audio not working on Mojave

### ISSUE THREAD

**Issue by Zerui18** [the-darkvoid/XPS9360-macOS#62]
Hi Darkvoid,

I was able to get Mojave working on my xps 9360 (stock except for DW1560) using your resources on this repo. However, there are a few issues that I'm encountering, namely no audio and Bluetooth. I have attached some debug files, can you help to look into this?

Thanks. 😀

(PS: VoodooI2C's not working as well but that's not a major issue)
[debug_28922.zip](https://github.com/the-darkvoid/XPS9360-macOS/files/2238456/debug_28922.zip)

**Comment by ver2go** [comment]
Did you run the audio patch script? `--patch-audio`
If you did, make sure the stock on is into loading. `kextstat | grep AppleALC`

For BT, I had to put the brcm* files in my /L/E

**Comment by Zerui18** [comment]
I can verify that AppleALC (1.3.0) has been loaded using kextstat. Besides AppleALC, I've also tried using the audio patch script (patched hda in /L/E), as well moving the patched hda into /S/L/E and replacing the stock one. However, none of these works.

As for the Brcm* kexts, they are all inside /L/E and loaded.

@ver2go Are you using the same laptop? If yes, are you able to get audio, bluetooth abd trackpad working using darkvoid's config and kexts?

**Comment by ver2go** [comment]
@Zerui18 kextstat | grep AppleALC should not be returning (not loaded) anything. So make sure you do not have the kext loading.
 
Exact same as thedarkvoids other than the ssd

**Comment by Zerui18** [comment]
Thanks @the-darkvoid for your response. 
I've tried the above steps but audio still doesn't work. Perhaps it's due to the inherent problem that Mojave's HDA doesn't support layout id 1?

@ver2go I'm not using AppleALC currently but just to clarify, were you saying that the normal behaviour of AppleALC.kext is that it should not be shown in kextstat?

**Comment by Zerui18** [comment]
Bluetooth is working after updating to the latest commit.

**Comment by ver2go** [comment]
@Zerui18 correct.  It should NOT show

> $ kextstat | grep AppleALC
$

**Comment by soto2080** [comment]
@Zerui18 I made some changes to scripts, now it supports 10.14, I had pulled request to @the-darkvoid .
If you wanna give it a try, see my requests.

**Comment by d3myz** [comment]
Hi There, my audio was working in this build before I installed the DW1830, not I can't get it to work. 
I've followed the steps above, when I do  kextstat | grep AppleALC, I get this. How do I get it not to show up? 

   18    0 0xffffff7f81197000 0x119000   0x119000   as.vit9696.AppleALC (1.4.0) 2009BAFC-6FB0-3304-B88E-94D2FCAE3E15 <17 13 8 6 5 3 2 1>

**Comment by d3myz** [comment]
I just updated to the latest version of clover, installed it and pasted the latest EFI folder and it worked.

**Comment by the-darkvoid** [comment]
> @Zerui18 I made some changes to scripts, now it supports 10.14, I had pulled request to @the-darkvoid .
> If you wanna give it a try, see my requests.

I'm sure those were pulled before, you are showing as a contributor. As indeed layout 0x01 is not supported on Mojave.
