### ISSUE TITLE
Brightness keys F11 F12 not working on latest version

### ISSUE THREAD

**Issue by 28spawn** [the-darkvoid/XPS9360-macOS#65]
It worked before the patch updates, now I have to use FN+S and FN+B to control screen brightness, can you check?

**Comment by egore24** [comment]
F11, F12 brightness works just fine here.

**Comment by ver2go** [comment]
In the not working camp.  Just updated, ran Kext Utility, rebooted.  Brightness keys not showing OSD and not making a change.

**Comment by the-darkvoid** [comment]
There have been no changed in brightness key.

4 things are needed for them to work:

- VoodooPS2Keyboard
- SSDT-BRT6 loading successfully
- Kext patch for change F%uT%04x to F%uTxxxx
- AppleBacklightInjector.kext

Make sure you have all 4 in place and loading successfully

**Comment by ver2go** [comment]
` kextstat |grep -i voodoo |grep -i ps2
   58    3 0xffffff7f834e2000 0xb000     0xb000     org.rehabman.voodoo.driver.PS2Controller (1.8.34) 1AF1E314-1FA8-3F4F-B299-934D39076D46 <11 7 5 4 3 1>
   90    0 0xffffff7f83530000 0x6000     0x6000     org.rehabman.voodoo.driver.PS2Keyboard (1.8.34) A219D398-E690-3C7F-B2D0-C65B8208353D <60 58 17 7 6 5 4 3 1>`

**Kext patch for change F%uT%04x to F%uTxxxx
**
_Not sure how to check for this, but I see the reference in config.plist_

`6:464  0:000  Inserting table[4]:SSDT-BRT6.aml from EFI\CLOVER\ACPI\patched: size=243 ... Success`


`kextstat |grep -i ackli
   52    1 0xffffff7f830b2000 0x6000     0x6000     com.apple.driver.AppleBacklightExpert (1.1.0) B914C331-D34D-3C2A-A213-B030389F577C <51 50 13 12 5 4 3>
   53    0 0xffffff7f830b8000 0x5000     0x5000     com.apple.driver.AppleBacklight (170.12.6) 5B2C1589-CD83-390D-83C1-E1F4A6CF6C6F <52 51 50 12 5 4 3>`

**Comment by trlsmax** [comment]
F11, F12 brightness works after upgrade here.

**Comment by the-darkvoid** [comment]
@cem2ran, @ver2go : Can you confirm commit 878ba92 resolves your issue?

**Comment by ver2go** [comment]
@the-darkvoid confirmed.  Working now at 878ba92
