### ISSUE TITLE
Bluetooth not available after wake up

### ISSUE THREAD

**Issue by ver2go** [the-darkvoid/XPS9360-macOS#69]
Bluetooth works on start up.  After some wake back up instance, the bluetooth icon will show
BT symbol with wavy line through it horizontally.
Clicking on it will say "Bluetooth: Not Available"

dmesg |grep -i blue output below.

`**** [IOBluetoothHostControllerUSBTransport][RequestTransportPowerStateChange] -- entering -- ON -> ON -- this = 0x3000 ****
**** [IOBluetoothHostControllerUSBTransport][RequestTransportPowerStateChange] -- exiting -- result = SUCCESS -- this = 0x3000 ****
**** [IOBluetoothHostController][RequestPowerStateChangeFromUserSpace] -- ON -> ON (thread: 0x5000) -- returning 0x0000 (kIOReturnSuccess)
**** [IOBluetoothHostControllerTransport][powerStateWillChangeTo] -- SleepType is kIOPMSleepTypeNormalSleep -- this = 0x3000 ****
**** [IOBluetoothHostControllerUSBTransport][setPowerStateWL] -- exiting -- Power state change completed -- microsecondsUntilComplete = 0 -- powerStateOrdinal = ON, originalPowerState = ON -> mPendingInternalPowerState = ON -- this = 0x3000 ****
**** [AppleBroadcomBluetoothHostController][SetVendorSpecificEventMask] -- Error! Beware Vendor Specific Set Event Mask command failed, and this could cause strange behavior -- Sleeping -- this = 0x2a80
**** [IOBluetoothHostControllerUSBTransport][StopInterruptPipeRead] -- mInterruptPipe->abort() returned 0x0000 (kIOReturnSuccess) ****
**** [BroadcomBluetoothHostControllerUSBTransport][WaitForAllIOsToBeAborted] -- SLEEP -> SLEEP -- before calling super::WaitForAllIOsToBeAborted() -- mLMPBulkInOutstandingIOCount = 0 -- this = 0xffffff80327a3000 ****
**** [IOBluetoothHostControllerUSBTransport][setPowerStateWL] -- exiting -- Power state change completed -- microsecondsUntilComplete = 0 -- powerStateOrdinal = IDLE, originalPowerState = ON -> mPendingInternalPowerState = SLEEP -- this = 0x3000 ****
**** [IOBluetoothHostControllerTransport][powerStateWillChangeTo] -- SleepType is kIOPMSleepTypeNormalSleep -- this = 0x3000 ****
**** [IOBluetoothHostControllerUSBTransport][StartBulkPipeRead] -- mBulkInPipe->clearStall (true) failed with error 0xE00002ED (kIOReturnNotResponding) -- 0x3000 ****
**** [IOBluetoothHostControllerUSBTransport][StartInterruptPipeRead] -- mInterruptPipe->clearStall (true) failed with error 0xE00002ED (kIOReturnNotResponding) -- 0x3000 ****
**** [IOBluetoothHostControllerUSBTransport][SetRemoteWakeUp] -- deviceRequest() failed: 0xE00002ED (kIOReturnNotResponding)
**** [IOBluetoothHostControllerUSBTransport][PrepareControllerWakeFromSleep] -- SLEEP -> ON -- SetRemoteWakeUp(TRUE) returned error 0xE00002ED (kIOReturnNotResponding) -- this = 0x3000 ****
**** [IOBluetoothHostControllerUSBTransport][DeviceRequestCompleteHandler] -- Received 0xE00002ED (kIOReturnNotResponding) -- 0x3000 ****
**** [IOBluetoothHostControllerUSBTransport][DoDeviceReset] -- PerformHardReset() -- reEnumerateOrReset = 1 (ReEnumerate Module) --  returned kIOReturnSuccess -- 0x3000 ****
**** [IOBluetoothHostControllerUSBTransport][terminateWL] -- entering -- mCurrentInternalPowerState = ON -- this = 0x3000 ****
**** [IOBluetoothHostControllerUSBTransport][terminateWL] -- exiting -- (matched on Device) -- this = 0x3000 ****
*** [IOBluetoothHostController][SendHCIRequestFormatted] -- Transport is inactive -- inOpCode = 0x0C01 (Set Event Mask), From: kernel_task (0), mNumberOfCommandsAllowedByHardware is 1, requestPtr = 0x6000 -- this = 0x2a80
*** [IOBluetoothHostController][SendHCIRequestFormatted] -- Transport is inactive -- inOpCode = 0x2001 (LE Set Event Mask), From: kernel_task (0), mNumberOfCommandsAllowedByHardware is 1, requestPtr = 0xa000 -- this = 0x2a80
**** [IOBluetoothHostControllerUSBTransport][setPowerStateWL] -- exiting -- Power state change completed -- microsecondsUntilComplete = 0 -- powerStateOrdinal = ON, originalPowerState = SLEEP -> mPendingInternalPowerState = ON -- this = 0x3000 ****
**** [IOBluetoothFamily][HardwareResetWL] -- entering  ****
**** [IOBluetoothFamily][HardwareResetWL] -- Either mActiveBluetoothHardware or mActiveBluetoothHardware->mBluetoothHostController is NULL -- cannot re-enumerate ****
**** [IOBluetoothFamily][HardwareResetWL] -- exiting  ****
BroadcomBluetoothHostControllerUSBTransport::handlePowerDomainWillChangeTo not in power tree`

**Comment by ver2go** [comment]
Closing this one.  I believe Logitech drivers are the issue. 
I've uninstalled them and now it is just the waiting game. It has taken several days for this issue to show up.  Will reopen if necessary.

**Comment by ver2go** [comment]
Sorry, re-opening.  Still happening with Logitech Options uninstalled.
I'm not sure what to grab to debug

`$kextstat |grep com.lo`
No ressults
`$dmesg |grep -i blue
**** [IOBluetoothHostControllerUSBTransport][setPowerStateWL] -- exiting -- Power state change completed -- microsecondsUntilComplete = 0 -- powerStateOrdinal = ON, originalPowerState = SLEEP -> mPendingInternalPowerState = ON -- this = 0x5800 ****
**** [IOBluetoothFamily][HardwareResetWL] -- entering  ****
**** [IOBluetoothFamily][HardwareResetWL] -- Either mActiveBluetoothHardware or mActiveBluetoothHardware->mBluetoothHostController is NULL -- cannot re-enumerate ****
**** [IOBluetoothFamily][HardwareResetWL] -- exiting  ****
`

**Comment by egore24** [comment]
I am experiencing this issue as well with the latest commit and Mojave installed.

**Comment by egore24** [comment]
This issue persists. Is it possible Darkwake is responsible for this? When waking, the machine displays a black screen. tapping a key activates the screen, then login. It would be nice to have the screen light up without needing the extra keystroke. Wondering if a different Darkwake choice would power up the bluetooth appropriately. Has anyone looked into this? Thanks.

**Comment by egore24** [comment]
Using Darkwake setting of 4 and moving BrcmFirmwareRepo.kext and BrcmPatchRAM2.kext to EFI/Clover/Kexts/Other has allowed Bluetooth to continue to be available after sleep.

**Comment by stepri** [comment]
Exact same problem here. No bluetooth after wake up.

**Comment by egore24** [comment]
> Exact same problem here. No bluetooth after wake up.

Have you tried my comment just above yours? Since doing that, bluetooth has been just fine for me.

**Comment by egore24** [comment]
https://www.tonymacx86.com/threads/solved-bcm94352z-bluetooth-not-working-after-wake.255014/page-2#post-1799915

Experimenting with this now. Seems promising so far.

**Comment by egore24** [comment]
It did help, but I do not remember what the timings were. I did a fresh install which completely remedied the issue.

**Comment by the-darkvoid** [comment]
Rehabman pointed out this issue before, this usually happens because a driver or application is locking the USB port.

Even Google Chrome locks the USB ports by default.

**Comment by magneticchen** [comment]
Are there any solutions for this kind of issue?

**Comment by syifan** [comment]
I am experiencing the same problem. This is the biggest issue that makes it a not perfect Hackintosh. Can this be solved?

**Comment by mpross512** [comment]
Also having this issue. I've tried it with and without different timings, still no luck. 

One other thing to note is that sometimes when I boot the machine I get the message (in verbose):
`kextd stall[0], (60s): AppleUSBHostLegacy Client, **BrcmPatchRam2,** IOUSBHostInterface, SMCSMBusController`

**Comment by bormanua** [comment]
Is there any solutions to this issue ?
