### ISSUE TITLE
xps13 9360 i5 8250u

### ISSUE THREAD

**Issue by 820Mockingjay** [the-darkvoid/XPS9360-macOS#70]
hello i ues XPS13 9360
I5 8250U
8G
512 Samsung 960 PRO
Sharp  QHD+ (3200x1800) Touchscreen display
Dell DW1560 Wireless
then i cant ues your efi to insert install system 
can you help me to make a efi for my configuration ？
My email hjw921643026@gmail.com 
Thank you very much

**Comment by SakuraTime** [comment]
Do your homework and research before asking questions here, please.
