### ISSUE TITLE
capslock key misbehave after modify keys

### ISSUE THREAD

**Issue by lisztli** [the-darkvoid/XPS9360-macOS#71]
After install 10.13, I modify capslock key to command, try to use it as command key. Then the light on capslock key lighted and will never turn off, and the keyboard behaves like the command key is pressed without releasing.

**Comment by the-darkvoid** [comment]
@lisztli I've never tried to use the capslock as the command key. I'd actually suggest using the Windows key as the command key.

However, the problem would be potentially related to the VoodooPS2Keyboard drivers, so you'd need to report it there. I think it might not be resolvable though.
