### ISSUE TITLE
DW1560

### ISSUE THREAD

**Issue by kserxes** [the-darkvoid/XPS9360-macOS#72]
I know this is technically not an issue related to the content of this repo but as the DW1560 Wifi/BT card is the one suggested for the best outcome in macOS it is still connected and a lot of people using this excellent bundle for macOS High Sierra should be in the same boat. I'd like to know if any of you dual booting with Windows 10 also battle with frequent lock-ups/freezing of Windows 10 after a few minutes of logging in? 
It clearly seems to be connected to the Wifi functionality of the DW1560 because when in Airplane mode or disabling Wifi this does not happen, but after enabling, it will again only take 30 seconds or a few minutes max until Windows completely freezes and won't get responsive again unless doing a hard reset.

Anyone fixed this issue, or does not experience it after exchanging the stock Wifi/BT with the DW1560?

Thanks,
Juergen

**Comment by businessman9** [comment]
Using DW1560 here and both Win/Mac work well.

**Comment by kserxes** [comment]
If you don‘t mind what are your Bluetooth and WiFi devices called in Device Manager in Windows 10 and what driver versions are you using, or what drivers did you install?

Thanks,
Juergen

**Comment by jackno** [comment]
I also noticed Win10 constantly hanging while the DW1560 card was installed. I couldn't find a fix and had to switch back to the Killer 1535.

**Comment by the-darkvoid** [comment]
Windows 10 April update worked out of the box with my DW1560 [`14e4:43b1`]
