### ISSUE TITLE
Installer Still Waiting for Root Device

### ISSUE THREAD

**Issue by mpross512** [the-darkvoid/XPS9360-macOS#74]
After changing all my environment variables and using what I thought was the correct BIOS configuration on version 2.8.1, every time I boot the installer I get the prohibited sign with the error "Still waiting for root device". 

I'm using the DW1820A instead of the DW1560, could this be causing the issue? Maybe some incompatibility with the SSDT patches or something? Or am I missing some necessary boot flags?

My XPS configuration is the exact same as in the README, just copied the Clover folder from the repository.

**Comment by the-darkvoid** [comment]
Did you put your BIOS disk configuration to AHCI?

**Comment by mpross512** [comment]
Yes I did, but the problem occurs when booting from the USB installer, not the hard drive. Same result on the newest BIOS version and commit.

**Comment by mpross512** [comment]
Solved the issue. Having an unsupported wireless card seemed to cause this error.
