### ISSUE TITLE
Continuous hiss while using headphone

### ISSUE THREAD

**Issue by Mnkai** [the-darkvoid/XPS9360-macOS#77]
I'm using `--patch-hda` method.

Everything works well, but continuous hiss (white noise) can be observed while audio amp is on (not in powersaving).

Related solution (in Linux) is [this](https://wiki.archlinux.org/index.php/Dell_XPS_13_(9360)#Continuous_hissing_sound_with_headphones).

I also had this problem while using Arch Linux, and could solve this problem by setting Headphone Mic Boost to 10dB.

Is there any way to manually set this in macOS?

**Comment by the-darkvoid** [comment]
You could add custom CodecCommander.kext HDA verbs to archive what you want to do.
Or look into modifying the layout / platform plist files to add 10dB.

**Comment by imEgo** [comment]
> I'm using `--patch-hda` method.
> 
> Everything works well, but continuous hiss (white noise) can be observed while audio amp is on (not in powersaving).
> 
> Related solution (in Linux) is [this](https://wiki.archlinux.org/index.php/Dell_XPS_13_(9360)#Continuous_hissing_sound_with_headphones).
> 
> I also had this problem while using Arch Linux, and could solve this problem by setting Headphone Mic Boost to 10dB.
> 
> Is there any way to manually set this in macOS?

Thx, dude. Finally, I solved this problem after almost a year research.

use hda-verb to set amp gain manually:
./hda-verb 0x1a SET_AMP_GAIN_MUTE 0x5001
./hda-verb 0x1a SET_AMP_GAIN_MUTE 0x6001
OR
You can add command 01A5001 01A6001 to PinConfig or SSDT-ALC256.aml for Auto-Run

**Comment by Mnkai** [comment]
Since I’m not using XPS 13 anymore, I cannot test above solution is working, but in theory, it should work.

I will now close this issue thread.
