### ISSUE TITLE
Abnormal battery consumption

### ISSUE THREAD

**Issue by soto2080** [the-darkvoid/XPS9360-macOS#79]
My laptop info , 8250u and 8gb ram with a 1080p display, swapped with a mx500 SATA m.2 ssd ,SD card reader is disabled.

I often use my laptop in classes, so the battery backup is very important for me.
Another thing is that I am a CS student, though windows has a good power-management and good touchpad, I prefer to an unix-like OS.
So I decide to install macOS, for the unix-like and beautiful DE, but the annoying problem is power consumption is much more that other os.

Under Windows 10, Idle is about 4 watt/s and normal usage is about 6 or 7watts per second, heavy load will about to TDP. The average battery consumption is 1% for 10min pdf reading in power-save mode(cpu is locked at 800MHz). That mean I had 15 hours screen on time.
Under a well optimized linux, Idle only costs 2 watt per second , I know that sounds ridiculous but it's true.
As for macOS, Idle is about 6 or 7 watt/s and web browsing is about 10 watt/s , coding in VSCode is about 13 watt/s.
The consumption is relatively high compare to other OS,  and I had use cpu friend and data to inject frequency vector, the frequency of cpu seems normal(800MHz when Idle), but the battery still drain.

I guess that there are something had not set correctly, but when I compare to IOReg dump from real MBP, there are some different, one is Thunderbolt and the other is USB device and apple T2, and that also use HWP. But I think the problem is not relate to these difference.
But I had no clue to resolve the problem, any advice?

**Comment by ymmshi** [comment]
same problem here,and the processor stuck at 3.7ghz when waking from sleep

**Comment by ymmshi** [comment]
> > same problem here,and the processor stuck at 3.7ghz when waking from sleep
> 
> What method you use for audio, AppleALC or patched AppleHDA?
> AppleALC will cause cpu stuck at 3.7GHz.

thank u for your reply.I just remove AppleALC from kexts folder ,everything works well now!

**Comment by Suraj1006** [comment]
@soto2080 would you mind sharing your efi folder ? I just want to compare your CPU friend kext. I just can't get my processor stay at 800mhz .

**Comment by soto2080** [comment]
[CLOVER.zip](https://github.com/the-darkvoid/XPS9360-macOS/files/2458967/CLOVER.zip)
@Suraj1006 Here you go.

**Comment by soto2080** [comment]
@Suraj1006  Use 10.14.

**Comment by Suraj1006** [comment]
@soto2080 Gotcha

**Comment by ver2go** [comment]
Working for me as well, but I started from scratch for Mojave install to try to fix the disappearing issues for bluetooth.
I started with Darkvoid's repo, ran the XPS script for audio 

Then soto2080 graciously shared zipped.  So I took the difference and put it into my clover.  Also I did a diffmerge on config.plist
diffmerged the XPS script to apply the audio fixes (You could just copy the files over and enable it to launch at start up)

Not sure if any of that was required, but I was taking steps to isolate issues and learned a bit more about "hackintoshing" along the way.  

So far it has been working great.

Headphones work after sleep again now. Does take a second plug from time to time.
Knock on wood, so far no more "Bluetooth not available" after a few days

**Comment by Suraj1006** [comment]
@ver2go Same here, ran the script and got audio working . 
Tried using the latest vooodo but still couldn't get touchpad working
