### ISSUE TITLE
Stuck on BIOS 2.4.2

### ISSUE THREAD

**Issue by Acen-Fr** [the-darkvoid/XPS9360-macOS#8]
Hello, I'm stuck on BIOS 2.4.2 and I can't downgrade, I'd like to know if it could be a problem for hackintosh ?

**Comment by syncmaster851** [comment]
I'm on 2.3.1 so no answer for you , could you try it and feedback to the community?

**Comment by sbaier1** [comment]
im on 2.5.0 and don't have any issues. they also seem to have improved the fan control polling with the update so it's worth upgrading imo.

**Comment by Acen-Fr** [comment]
Good to know ! Thank you !
