### ISSUE TITLE
Bluetooth not working 10.13.6 on DW1560

### ISSUE THREAD

**Issue by ltanedo** [the-darkvoid/XPS9360-macOS#81]
Hey guys thanks so much for the work!  Currently I have a successful Hackintosh with a DW1560 card installed.  Wifi works flawlessly but Bluetooth is still unavailable.  I already installed the BrcmFirmwareRepo.kext, BrcmPatchRam2.kext, and the codec commander.kext into the L/E folder and rebuilt the kext cache? Does anyone have any idea on what I can do? Thanks!

**Comment by soto2080** [comment]
Bios settings needed to be set correctly.
Or macOS will not get Bluetooth device correctly.

**Comment by the-darkvoid** [comment]
You might want to validate your DW1560 device ID compared to the one documented in the README.
