### ISSUE TITLE
setup_var error

### ISSUE THREAD

**Issue by dontsave** [the-darkvoid/XPS9360-macOS#82]
Hi. I have this machine with i7-8550U BIOS 2.8.1. After using Unibeast, I replaced the CLOVER folder with the CLOVER folder in this repo, backed up Shell64U.efi, renamed DVMT.efi to Shell64U.efi, booted to clover, opened the uefi shell and ran setup_var, but I receive error: 

```
error: Usage: setup_var offset [setval]
```

what am I missing?

**Comment by Zerui18** [comment]
As the prompt says, the command setup_var requires arguments.

For example, to set the value at offset 0x785 to 0x06, run ‘setup_var 0x785 0x06’. Also note that running setup_var with only the first argument (offset) reads the value at the offset.

**Comment by the-darkvoid** [comment]
@Zerui18's answer is correct.

**Comment by dontsave** [comment]
Thanks I got it going!
