### ISSUE TITLE
Mojave ready?

### ISSUE THREAD

**Issue by egore24** [the-darkvoid/XPS9360-macOS#83]
Hello. Not an issue, but wondering if this repo is Mojave ready as is? Thanks.

**Comment by trlsmax** [comment]
I try it yesterday. Install and boot at the first time, then stuck at apple logo every time.

**Comment by businessman9** [comment]
I made a backup and update from app store, it took about an hour from downloading to finish. Everything looks good and even better.

**Comment by egore24** [comment]
@businessman9 any chance you could share your EFI folder and BIOS settings? Thank you!

**Comment by the-darkvoid** [comment]
I'm running Mojave at the moment without any issues. I'll be committing updates to the repository soon   after it is deemed stable.

**Comment by egore24** [comment]
Disregard all...I had been using the latest commit from here, but some of the drivers were causing a boot conflict. I rolled back to a previous set of drivers and all is good now.

**Comment by rozenmd** [comment]
@egore24 do you remember specifically which commit you used? Tried using latest and just get the same black screen when booting the installer

**Comment by ElieMyIdea** [comment]
Hi, 

I can't run osx Mojave upgrade :/
I'm getting :
"AppleLMUController : Could not get Smcprovider" 
While booting up on the installer..
