### ISSUE TITLE
[help] What's the different between a kext placed in /kexts and a kext in /CLOVER/kexts/Others in this repo?

### ISSUE THREAD

**Issue by simonla** [the-darkvoid/XPS9360-macOS#84]

**Comment by the-darkvoid** [comment]
Both the same. `/kexts` is just a repo of 3rd party kexts I'm using. It is mostly for people who have a Clover EFI installation deviating significantly from what is in the repository.

`/Clover` is a representation of the default Clover installation in the repo.
