### ISSUE TITLE
Mojave - No sound/devices

### ISSUE THREAD

**Issue by egore24** [the-darkvoid/XPS9360-macOS#85]
Hello. I have removed AppleALC.kext and ran the --patch-hda which did install the two kexts to L/E, but my machine has no sound. No sound devices in the CP either. Any ideas/thoughts? Thanks.

**Comment by businessman9** [comment]
I also have sound problem in Mojave.
Uupdated from High Sierra and the sound worked ok,
I tried to fix sometimes headphone not working issue and tested patchhda and newer AppleALC, 
but no sound at all, no sound device anymore. I have to roll back to High Sierra from backup and update again, sound is there! So maybe something about sound is changed in Mojave

**Comment by the-darkvoid** [comment]
Only AppleALC works (with layout 11) in Mojave. `--patch-hda` is not functional in Mojave as of now.

**Comment by woolmonkey** [comment]
Ok is there anymore needed for this?  I have disabled the HDA patching in clover injected the 11 layout id.  But I still don't get audio.  Not sure what I am missing.

**Comment by TrustedDeveloper** [comment]
Same here. What are the steps needed to enable audio on Mojave?

**Comment by rama1981** [comment]
when you did the update form HS - Delete your "AppleHDA_ALC256.kext" from //Library/Extensions/

**Comment by woolmonkey** [comment]
I never updated just installed Mojave directly.  What about the clover audio patches do those have to be disabled?  Do they actually patch the kext or just the cache.  The audio should work I believe but it isn't.

**Comment by TrustedDeveloper** [comment]
Did some Googling and figured it out.
Download Clover Configurator and add the following to your Boot Arguments:
`alcid=11 `
Feel quite stupid for not researching this a little more. Sorry for taking up your time.

**Comment by egore24** [comment]
> Did some Googling and figured it out @egore24 , @businessman9.
> Download Clover Configurator and add the following to your Boot Arguments:
> `alcid=11`
> Feel quite stupid for not researching this a little more. Sorry for taking up your time, @the-darkvoid.

This in fact is the solution for the issue, using Apple_ALC.kext This needs to be included in the next commit. No other offered solutions worked. Thanks!

**Comment by 0xHJK** [comment]
> Did some Googling and figured it out @egore24 , @businessman9.
> Download Clover Configurator and add the following to your Boot Arguments:
> `alcid=11`
> Feel quite stupid for not researching this a little more. Sorry for taking up your time, @the-darkvoid.

It  is helpful. Thanks for your solution.

**Comment by the-darkvoid** [comment]
Note that the latest update for Mojave brings back the native AppleHDA injector with a layout id of 2.

Two options:

- Use AppleALC with layout id 11 (0x0b) either through boot argument, clover config or SSDT-Config.aml
   Ensure to remove AppleHDA_ALC256.kext from /Library/Extensions AND rebuild your kernel cache in this case

- Use ./XPS9360.sh --patch-hda with layout id 2, SSDT-Config.aml in the repo is already preconfigured for that
   Ensure to remove AppleALC.kext from the kext/Other folder on your EFI volume in this case.

**Comment by jafd** [comment]
Hmm, with layout-id = 2 I don't have any input devices; is it expected?
