### ISSUE TITLE
Right-click not working

### ISSUE THREAD

**Issue by kserxes** [the-darkvoid/XPS9360-macOS#86]
Hi,

After I updated to the latest commit I noticed that a right-click (secondary click) on the trackpad (actual click on the lower right side of the trackpad) no longer works. I was a few commits behind before so I cannot really tell when it started appearing but am pretty sure it used to work.
Tapping with two fingers for a secondary click works.
Any ideas?

Thanks,
Juergen

**Comment by the-darkvoid** [comment]
It seems to be an issue in the native touchpad implementation now used in VoodooI2C.
Best to report it there as an issue so it can it fixed upstream.

https://github.com/alexandred/VoodooI2C

Workaround for now is to use two-finger click/tap for alternate click, or downgrade VoodooI2C.

**Comment by dderrida** [comment]
hi
I also have the same problem. 
I will try to downgrade. just wondering which is the last version that was working.
thanks

**Comment by rostopira** [comment]
Yep, same here

**Comment by mpross512** [comment]
If you manually build the latest commit for VoodooI2C you can solve the issue

**Comment by rostopira** [comment]
@mpross512 could you share your build, please? (=

**Comment by mpross512** [comment]
[VoodooI2C.kext.zip](https://github.com/the-darkvoid/XPS9360-macOS/files/2754704/VoodooI2C.kext.zip)

Try that. After installing that and rebooting, you have to go into your trackpad settings and change the secondary click action to clicking in the lower right of the trackpad instead of two-finger click.
