### ISSUE TITLE
Expected battery life?

### ISSUE THREAD

**Issue by dontsave** [the-darkvoid/XPS9360-macOS#87]
Hi

First I just want to say thanks for your work putting this repo together. I have High Sierra running on my XPS 13 9360 with QHD+, touchscreen, wifi/bt, and sound all working. I am wondering what kind of battery life I should expect with this configuration? It currently feels like I'm getting around 4.5 to 5 hours with basic usage and screen brightness set to 80%. Does that seem correct?

Intel Power Gadget doesn't show particularly high power usage at idle, and under basic use, temps are around 55C. Activity monitor shows normal CPU usage. 

I have the i7-8550U and included the 2 prebuilt cpufriend kexts in Clover's kexts/other folder.

I have not undervolted or applied any patches for my 512gb Toshiba nvme drive. I have also not disabled the touchscreen yet.

I'm mostly curious if this battery life is what I should be expecting with the current state of my configuration, or if it should be better. I would guess the QHD screen is eating up a lot of power, but possibly the touch screen is as well? Any suggestions?

**Comment by the-darkvoid** [comment]
The touchscreen uses some amount of power. You can easily disable it through the BIOS.
I'm sure more power reduction can be achieved, but I haven't particularly looked into it more.

Some of the guys on tonymacx86 have looked into it and would probably welcome more insights and feedback.

**Comment by dontsave** [comment]
Thanks, I'll look into disabling it. Does 4-5 hours of battery life seem to be what you're getting with this config? Most people seem to not have the QHD/touch screen, so I'm having trouble judging what the average is

**Comment by rozenmd** [comment]
I have the same setup as you - doing frontend development (think chrome+6 tabs, iTerm, VS Code, Spotify) I get about 4-5 hours.

**Comment by soto2080** [comment]
8250u and a FHD display, I got about 6~8 hours when web surfing and some social apps.

**Comment by dontsave** [comment]
Thanks all. It seems the QHD+ screen eats a lot of battery vs FHD. No real surprise there. Closing the issue now
