### ISSUE TITLE
Freezing mouse when making circles

### ISSUE THREAD

**Issue by Jern97** [the-darkvoid/XPS9360-macOS#88]
Since the latest update of VoodooI2C i'm having a weird bug. If I draw a circle using the trackpad continuously I can see how it teleports in the last known direction of the circle - exactly every second, which makes it impossible to do a circle.

It is exactly the same behaviour as [this issue](https://github.com/alexandred/VoodooI2C/issues/113
) describes:

The solution (for now) is to delete the ACPIBatteryManager kext. This indeed works and now the pointer doesn't jump around anymore.

The problem is that I am not able to get the battery indicator working again. In the issue they suggest to use SMCBatteryManager instead but I can't get it to work and to be fair, it's a little bit over my head. I've added the 2 kexts and updated my clover to Rehabman's fork (as suggested) but I can't get the kexts to load.

If other users are experiencing the same bug maybe someone with a more knowledge can look into this.

Thanks!

EDIT: It only glitches when using the battery.

**Comment by the-darkvoid** [comment]
Git repo now uses VirtualSMC.
