### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by kaitoAckerman** [the-darkvoid/XPS9360-macOS#89]
Where do I find getting started guide ?. A step by step guide specifically for xps 13 9360

**Comment by landmarked** [comment]
Have a look at 

https://www.tonymacx86.com/threads/guide-dell-xps-13-9360-on-macos-sierra-10-12-x-lts-long-term-support-guide.213141/

You could follow that guide, or get some background to follow the more concise instructions provided with this distribution

**Comment by kaitoAckerman** [comment]
Hmm, I think I get it. 

But for a beginner like me, that [threads](https://www.tonymacx86.com/threads/guide-dell-xps-13-9360-on-macos-sierra-10-12-x-lts-long-term-support-guide.213141/) is a bit too complicated for me to understand. And require me to dig more resources on internet to understand more.

Is there any future plan for this repo to add a beginner guide based on your or other experience running macos on specifically xps 13 6390 laptop. What a beginner like me need to know and how to do in just one place. Which is in this repo.

So we can share what works and what not? I guess.

**Comment by the-darkvoid** [comment]
@kaitoAckerman : Running macOS on unsupported hardware is by nature a complex project.
As @landmarked suggested, the forums are the best way to learn.

I created this repo simply to share a sample setup for the XPS 9360 as I use it, over time others have found it handy as a reference, but it is by no means a complete end-to-end guide.
