### ISSUE TITLE
A little help for a newbie

### ISSUE THREAD

**Issue by azapicoe** [the-darkvoid/XPS9360-macOS#9]
Hi darkvoid, thanks for all your work. Im currently running an almost perfect version in this laptop, i followed this guide: https://www.tonymacx86.com/threads/guide-dell-xps-13-9360-on-macos-sierra-10-12-x-lts-long-term-support-guide.213141/
And i want to update to high sierra. I have a little newbie questions so i hope you can answer them.
1. Will i be able to update to high sierra using the appstore?
2. Should i update bios to your version before or after installing?
3. Why your repo have a CLOVER folder that i guess its the bootloader configured, but also have more folders in /.
Thanks for your work and for your help 👍

**Comment by the-darkvoid** [comment]
1. Better do a clean re-installation across main OS version
2. Do not update past the version documented in the readme to ensure everything works
3. There is a pre-built CLOVER folder, as well as all the source files used to build it. Ideally you'd only need the CLOVER folder.

Using the pre-built CLOVER folder makes it easy to apply updates as I commit them to the repository.
