### ISSUE TITLE
Bluetooth not working with Foxconn 0x0489:0xe07a

### ISSUE THREAD

**Issue by dderrida** [the-darkvoid/XPS9360-macOS#91]
Any chance to have this DW1560 card supported?
WiFi is detected as AirPort and works perfectly well.
Bluetooth is detected but does not work.

thanks

**Comment by the-darkvoid** [comment]
As you closed this, I assume you resolved the issue? Any changes which should go into the repo?

**Comment by dderrida** [comment]
No. Just an installation problem

**Comment by WentaoRen** [comment]
> No. Just an installation problem

you mean the dw1560 installation problem？ I have this problem too
