### ISSUE TITLE
TB3 not work most of time

### ISSUE THREAD

**Issue by soto2080** [the-darkvoid/XPS9360-macOS#92]
My tb3 port sometime works, but most not.
And I am wondering if there a fix for it as I seen [the post](https://www.insanelymac.com/forum/topic/323540-thunderbolt-drivers/?page=13) on Insanelymac.

A fully working tb3 with a type c port will be very good.

**Comment by the-darkvoid** [comment]
@13xps,

Can you provide more information on what patches you applied to make your type C port work?

**Comment by soto2080** [comment]
@the-darkvoid  I use your config, and I got my Dell TB15 thunderbolt dock working fine(Yes all features are fine).
But need to plug in before open lid(wake)  or power on computer.

**Comment by the-darkvoid** [comment]
@soto2080,

That is expected. This is how it works for me exactly. Either plug it in before boot, or when sleeping.
After that all works fine.

Hotplugging into an already running system does not work, no known work arounds at this time.
