### ISSUE TITLE
external 4K at 60hz possible?

### ISSUE THREAD

**Issue by dontsave** [the-darkvoid/XPS9360-macOS#93]
I have this exact configuration and an external 4K monitor, and I can get QHD @ 60hz on it, and I can get 4K @ 30hz on it, but I can't get 4K at 60hz. It works in windows using a USB-C to displayport adapter, but not OS X. Anyone have any luck with this?

**Comment by iarnihc** [comment]
My 4k monitor(P2415Q) can get  4K at 60hz.
Sleep the xps until  the power light goes out(maybe need 10s)
then wake up it and connect to the monitor.
The wire is type-c to dp.

**Comment by dontsave** [comment]
Huh that's interesting. I'll try that method tomorrow. Why does sleeping it beforehand work? 

I have a type-c to dp connection and currently when I try to connect to 4k without specifying 30hz it simply won't display anything. My monitor is an LG 27UD58-B. The cable I'm using is just a cheap USB C to DP cable from amazon.

What's your configuration? Do you have the QHD+ version of the 9360?

**Comment by iarnihc** [comment]
Actually, I don't know why :) , but it works. If you don't reboot, it will always work, support hot swap too.
My configuration from the darkvoid's configuration, but my xps is FHD version of the 9360(i5 8250U).
Good luck~

**Comment by dontsave** [comment]
wow i can't believe that worked!!! how did you even figure that out
