### ISSUE TITLE
Fans not spinning up in time.  No fan sensors.

### ISSUE THREAD

**Issue by DaveFlowberries** [the-darkvoid/XPS9360-macOS#97]
Same config as you, only difference is I have the stock Toshiba NVME on Mojave with APFS and did not 4k sector format.

When loading the CPU fans don't spin up until temp hits 80c+, at which time it thermal throttles to 2ghz. 

The fan profile is missing from HWMonitor, so I am assuming something in my config is not setup correctly.

Used the latest files from your repo. (not using ACPIBatteryManager.kext)

Am I missing something? 

Thank you for your time and for sharing these with us, greatly appreciated!

**Comment by the-darkvoid** [comment]
The latest VirtualSMC approach does not have the fan sensors implemented.
However thermal throttle and fans are handled by the BIOS, nothing to do with macOS.

I do plan to implement the sensors, but it would be only allowing you to see them in HWMonitor, it would not change anything with regards to the thermal profile.

**Comment by DaveFlowberries** [comment]
OK, got it, thanks. Have you successfully modified the bios to prevent the said behavior? if so, do you mind letting me know what you did? I did not see those options in bios, so assuming it will need to be patched somehow via setup_var ?
