### ISSUE TITLE
Scaling does not work correctly. 

### ISSUE THREAD

**Issue by 13xps** [the-darkvoid/XPS9360-macOS#99]
All scaling options result in blurry text, and the first two scaling options don't do anything at all. Only the "default for display" looks clean. Is there a way to let it scale correctly, and without loss in visual quality? Thanks. I am trying to make everything a little bigger.

**Comment by rama1981** [comment]
Use RDM App. Works perfekt with my UHD.

**Comment by 13xps** [comment]
Thanks, I tried it, unfortunately the next biggest setting up that HiDPI was too big, oh well, not a big deal I guess, looks great now, just a bit smaller than i would like.
